### ISSUE TITLE
An error on UI load

### ISSUE THREAD

**Issue by smithdws1** [BreakBB/ExtendedCharacterStats#102]
## Bug description

Load into the WoW Classic; also happens on /reload ui
Date: 2021-02-27 07:46:14
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\ExtendedCharacterStats\ECS.lua line 48:
   attempt to index field 'general' (a nil value)
Debug:
   [C]: ?
   ExtendedCharacterStats\ECS.lua:48:
      ExtendedCharacterStats\ECS.lua:41
   ExtendedCharacterStats\ECS.lua:31:
      ExtendedCharacterStats\ECS.lua:28
Locals:

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AAPClassic, v0.13
  Atlas, vv1.47.03.11304.00
  AtlasClassicWoW, vv1.47.02.11304.00
  AtlasLootClassic, vv1.5.8
  AtlasLootClassicData, vv1.5.8
  AtlasLootClassicDungeonsAndRaids, vv1.5.8
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v9.0.4
  Bartender4, v4.10.6
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  BiSTracker, v3.3
  ClassicAuraDurations, v1.13.61
  ClassicSpellActivations, v
  DBMCore, v1.13.67
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Decursive, v2.7.8
  Details, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DugisGuideViewerZ, v1.08
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  ExtendedCharacterStats, v2.7.0
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v1.13.6.11306 <none>
  (ck=4bc)

Date: 2021-02-27 07:46:17
ID: 2
Error occured in: Global
Count: 1
Message: ...face\AddOns\ExtendedCharacterStats\Modules\Stats.lua line 44:
   attempt to index field 'general' (a nil value)
Debug:
   [C]: ?
   ...face\AddOns\ExtendedCharacterStats\Modules\Stats.lua:44: CreateWindow()
   ExtendedCharacterStats\ECS.lua:102:
      ExtendedCharacterStats\ECS.lua:100
   ExtendedCharacterStats\ECS.lua:35:
      ExtendedCharacterStats\ECS.lua:28
Locals:

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AAPClassic, v0.13
  Atlas, vv1.47.03.11304.00
  AtlasClassicWoW, vv1.47.02.11304.00
  AtlasLootClassic, vv1.5.8
  AtlasLootClassicData, vv1.5.8
  AtlasLootClassicDungeonsAndRaids, vv1.5.8
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v9.0.4
  Bartender4, v4.10.6
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  BiSTracker, v3.3
  ClassicAuraDurations, v1.13.61
  ClassicSpellActivations, v
  DBMCore, v1.13.67
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Decursive, v2.7.8
  Details, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  DugisGuideViewerZ, v1.08
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  ExtendedCharacterStats, v2.7.0
  GatherMate2, v1.45.5
  Informant, v8.2.6374 (SwimmingSeadragon)
  OmniCC, v9.0.5
  PallyPower, vv1.2.27-classic
  Questie, v6.2.4
  Recount, vv1.13.5c
  SexyMap, vv5-classic
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  TomTom, vv11306-1.2.0
  WeakAuras, v3.1.8
  BlizRuntimeLib_enUS v1.13.6.11306 <none>
  (ck=598)

**Comment by BreakBB** [comment]
Hey @smithdws1 sorry for the late response.

Are you sure you are using the latest version of ECS? You could try to reset ECS by running the following script and then do a `/reload`:

`/run ExtendedCharacterStats = nil`
