### ISSUE TITLE
Add Armor Penetration for TBC

### ISSUE THREAD

**Issue by BreakBB** [BreakBB/ExtendedCharacterStats#105]
## Description

https://wowpedia.fandom.com/wiki/API_GetArmorPenetration

**Comment by tunder** [comment]
i would love to see added in the addon. thanks

**Comment by BreakBB** [comment]
Hey @tunder Yeah I wanted to add this for quite some time now, but didn't find the time 🙈 I will try to get it implemented in the next days!

**Comment by BreakBB** [comment]
Another follow up on this. I was on vacation and didn't find the time yet to get this finally done.

I hope to get it done this week and ship it right away.
