### ISSUE TITLE
UI Error

### ISSUE THREAD

**Issue by Tanae** [BreakBB/ExtendedCharacterStats#106]
## Bug description
Saw this working with a level 60 in Shadowlands in a WoW Facebook group but it bugs in retail. Any help?

## Version
2.8.0-tbc

**Comment by BreakBB** [comment]
ECS is not meant to work on retail @Tanae 🤔 Interesting someone uses it, I don't really see the benefit though. Must be some sort of own implementation.

**Comment by BreakBB** [comment]
Closing this as it seems not relevant anymore.
