### ISSUE TITLE
MP5 counter doesn't count Water Shield

### ISSUE THREAD

**Issue by silverhawke249** [BreakBB/ExtendedCharacterStats#110]
## Bug description
What title says. Most likely doesn't consider bonuses that affect Water Shield's MP5 either.

## Screenshots
![image](https://user-images.githubusercontent.com/50395934/115968636-65076800-a56b-11eb-803a-67f3b813b43e.png)
MP5 from buffs should be 50 MP5. Note the blank line for Spell Crit as well -- probably it could be removed?

## Version
2.8.1

**Comment by BreakBB** [comment]
Thanks for pointing this out @silverhawke249 Water Shield is not considered at all atm.

The Spell Crit value has just been fixed :)
