### ISSUE TITLE
Wrong defense value shown

### ISSUE THREAD

**Issue by Androgan** [BreakBB/ExtendedCharacterStats#111]
## Bug description

For my Alliance-Warri under Defense it shows 308 + 150 although it should be 300 + 8 from talents + 142 from gear.
The current total is 8 to high as it seems to count the talent bonus into the base value and the added bonus

![Defense](https://user-images.githubusercontent.com/32416270/116107925-bb7fbe00-a6b3-11eb-947a-11bf8cd9783d.png)

## Version

Using ECS v2.8.1 on WoW-Classic

**Comment by BreakBB** [comment]
Hmmm... ECS might calculate the talents twice 🤔 

Could you run the following command and report the output @Androgan ?

`/dump GetSkillLineInfo(15)`?

You might need to change the number `15` to something higher/lower (it is the line number in the Skills tab including headers).

The output should look like this:

![grafik](https://user-images.githubusercontent.com/33514570/117042899-d635e080-ad0c-11eb-8e77-99cbfdfbb906.png)

**Comment by Androgan** [comment]
Here you go, my gear changed a bit though. I am now at 150 defense from gear and still 8 points from talents

![dump](https://user-images.githubusercontent.com/32416270/118414481-1437ea80-b6a5-11eb-8bd6-10932f918aa5.png)
