### ISSUE TITLE
"GetExpertise" bug

### ISSUE THREAD

**Issue by angrylemons** [BreakBB/ExtendedCharacterStats#114]
When entering combat and exiting combat this error displays. Love the addon and hope this gets fixed! :)

**Page 1**

Message: ...AddOns\ExtendedCharacterStats\Modules\Data\Melee.lua:99: attempt to call global 'GetExpertise' (a nil value)
Time: Wed May 12 11:43:33 2021
Count: 13
Stack: ...AddOns\ExtendedCharacterStats\Modules\Data\Melee.lua:99: attempt to call global 'GetExpertise' (a nil value)
...AddOns\ExtendedCharacterStats\Modules\Data\Melee.lua:99: in function <...AddOns\ExtendedCharacterStats\Modules\Data\Melee.lua:98>
(tail call): ?
(tail call): ?
...face\AddOns\ExtendedCharacterStats\Modules\Stats.lua:164: in function <...face\AddOns\ExtendedCharacterStats\Modules\Stats.lua:162>
...face\AddOns\ExtendedCharacterStats\Modules\Stats.lua:323: in function <...face\AddOns\ExtendedCharacterStats\Modules\Stats.lua:312>
...face\AddOns\ExtendedCharacterStats\Modules\Stats.lua:305: in function `UpdateInformation'
Interface\AddOns\ExtendedCharacterStats\ECS.lua:131: in function <Interface\AddOns\ExtendedCharacterStats\ECS.lua:130>

Locals: self = <table> {
 HUNTER = 3
 FIRE_SCHOOL = 3
 HOLY_SCHOOL = 2
 ROGUE = 4
 MAGE = 8
 IsSetBonusActive = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\ItemSets.lua:115
 GetRangedAttackSpeed = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\Ranged.lua:29
 SpellHitBonus = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\SpellHit.lua:31
 GetBlockValue = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\Defense.lua:71
 DRUID = 11
 GetMP5FromSpirit = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\MP5.lua:64
 RangedCrit = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\Ranged.lua:35
 MeleeHitBonus = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\Melee.lua:39
 SpellMissChanceBossLevel = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\SpellHit.lua:59
 SpellMissChanceSameLevel = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\SpellHit.lua:41
 GetSpellPenetration = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\SpellCrit.lua:112
 GetSpellCrit = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\SpellCrit.lua:15
 RangeMissChanceBossLevel = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\Ranged.lua:86
 GetArmorValue = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\Defense.lua:10
 RangeHitBonus = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\Ranged.lua:63
 WARLOCK = 9
 GetParryChance = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\Defense.lua:61
 GetHealingPower = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\Data.lua:39
 GetMP5WhileCasting = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\MP5.lua:74
 GetMP5FromBuffs = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\MP5.lua:115
 GetRangeAttackPower = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\Ranged.lua:12
 HasNatureCritBonusModifier = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\ItemSets.lua:100
 MeleeHitMissChanceSameLevel = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\Melee.lua:44
 SHADOW_SCHOOL = 6
 SHAMAN = 7
 SpellPenetration = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\Data.lua:34
 NATURE_SCHOOL = 4
 ARCANE_SCHOOL = 7
 GetExpertise = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\Melee.lua:98
 GetSpellDmg = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\Data.lua:14
 GetMeleeAttackPower = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\Melee.lua:8
 MeleeCrit = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\Melee.lua:26
 GetMeleeAttackSpeedOffHand = <function> defined @Interface\AddOns\ExtendedCharacterStat

Message: ...AddOns\ExtendedCharacterStats\Modules\Data\Melee.lua:99: attempt to call global 'GetExpertise' (a nil value)
Time: Wed May 12 11:46:21 2021
Count: 6
Stack: ...AddOns\ExtendedCharacterStats\Modules\Data\Melee.lua:99: attempt to call global 'GetExpertise' (a nil value)
...AddOns\ExtendedCharacterStats\Modules\Data\Melee.lua:99: in function <...AddOns\ExtendedCharacterStats\Modules\Data\Melee.lua:98>
(tail call): ?
(tail call): ?
...face\AddOns\ExtendedCharacterStats\Modules\Stats.lua:164: in function <...face\AddOns\ExtendedCharacterStats\Modules\Stats.lua:162>
...face\AddOns\ExtendedCharacterStats\Modules\Stats.lua:323: in function <...face\AddOns\ExtendedCharacterStats\Modules\Stats.lua:312>
...face\AddOns\ExtendedCharacterStats\Modules\Stats.lua:305: in function `UpdateInformation'
Interface\AddOns\ExtendedCharacterStats\ECS.lua:127: in function <Interface\AddOns\ExtendedCharacterStats\ECS.lua:119>

**Page 2**

Locals: self = <table> {
 HUNTER = 3
 FIRE_SCHOOL = 3
 HOLY_SCHOOL = 2
 ROGUE = 4
 MAGE = 8
 IsSetBonusActive = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\ItemSets.lua:115
 GetRangedAttackSpeed = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\Ranged.lua:29
 SpellHitBonus = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\SpellHit.lua:31
 GetBlockValue = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\Defense.lua:71
 DRUID = 11
 GetMP5FromSpirit = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\MP5.lua:64
 RangedCrit = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\Ranged.lua:35
 MeleeHitBonus = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\Melee.lua:39
 SpellMissChanceBossLevel = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\SpellHit.lua:59
 SpellMissChanceSameLevel = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\SpellHit.lua:41
 GetSpellPenetration = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\SpellCrit.lua:112
 GetSpellCrit = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\SpellCrit.lua:15
 RangeMissChanceBossLevel = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\Ranged.lua:86
 GetArmorValue = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\Defense.lua:10
 RangeHitBonus = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\Ranged.lua:63
 WARLOCK = 9
 GetParryChance = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\Defense.lua:61
 GetHealingPower = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\Data.lua:39
 GetMP5WhileCasting = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\MP5.lua:74
 GetMP5FromBuffs = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\MP5.lua:115
 GetRangeAttackPower = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\Ranged.lua:12
 HasNatureCritBonusModifier = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\ItemSets.lua:100
 MeleeHitMissChanceSameLevel = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\Melee.lua:44
 SHADOW_SCHOOL = 6
 SHAMAN = 7
 SpellPenetration = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\Data.lua:34
 NATURE_SCHOOL = 4
 ARCANE_SCHOOL = 7
 GetExpertise = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\Melee.lua:98
 GetSpellDmg = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\Data.lua:14
 GetMeleeAttackPower = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\Melee.lua:8
 MeleeCrit = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\Melee.lua:26
 GetMeleeAttackSpeedOffHand = <function> defined @Interface\AddOns\ExtendedCharacterStats

**Comment by BreakBB** [comment]
Hey @angrylemons I guess you are running this on Classic, right? Not TBC beta?

**Comment by angrylemons** [comment]
@BreakBB yes it is the latest version of classic.
