### ISSUE TITLE
TBC Classic Spell Hit/Crit Racials, Talents or Auras (Totems) not considered

### ISSUE THREAD

**Issue by Chris-dot-net** [BreakBB/ExtendedCharacterStats#119]
## Bug description
Elemental Shaman Hit Talents, Totem of Wrath, or Draenei Aura (Shaman got Spellhit Aura) not shown in ECS.

Additionally there are now more magic-class-specific hit and crit talents (nature for shaman esp). Those hit is not shown (because it is not for all magic schools, even though it is for all magic schools of the class). 

Totem of Wrath should grant 3% spellhit and 3% spellcrit, both not reflected by ecs.

## Screenshots
Orc Elemental Shaman with Totem of Wrath and 24 spellhit equipped (3% at 60) only showing 3% spell hit (instead of 6%)
![WoWScrnShot_052021_144048](https://user-images.githubusercontent.com/73933965/118980061-64e76600-b979-11eb-8b3f-9f77483bd6c9.jpg)
Draenei Elemental Shaman w/o specific Talents but Aura which is not reflected by ecs
![WoWScrnShot_052021_143900](https://user-images.githubusercontent.com/73933965/118980065-657ffc80-b979-11eb-8922-e76744bf0329.jpg)

## Version
2.8.3

**Comment by BreakBB** [comment]
Hey @Chris-dot-net thanks for the detailed report on this. The next release v2.8.4 will reflects many new Shaman Talents. Let me know if you find anything else I missed 👍🏻
