### ISSUE TITLE
Miss-Chance can be above 100%

### ISSUE THREAD

**Issue by BreakBB** [BreakBB/ExtendedCharacterStats#12]
## Screenshots

![image](https://user-images.githubusercontent.com/33514570/72664336-ec773a80-39fc-11ea-9a0e-10c86ac737e0.png)

## Version

v2.2.3

**Comment by byeuji** [comment]
I have this as well -- 113% and 119%. And in addition, as a druid withy +9% hit equipped, my miss chance shows as 1% at level, 7% lvl +3. /dump GetHitModifier() produces "[1]=9"

Unless the algorithm changed, I should be 0% miss on both of those.

**Comment by byeuji** [comment]
Ah, I shifted and the deficit went away. Nevermind!

**Comment by BreakBB** [comment]
@byeuji Yeah without shapewhift the values are calculated your weapon skill.

**Comment by byeuji** [comment]
> @byeuji Yeah without shapewhift the values are calculated your weapon skill.

Yeah, 100% good design. Thanks for following up :)

**Comment by BreakBB** [comment]
@byeuji Thanks for the report though! :+1: Glad you like it :)
