### ISSUE TITLE
Spell Hit bonus for mage too high.

### ISSUE THREAD

**Issue by Hoedown9270** [BreakBB/ExtendedCharacterStats#122]
## Bug description
Spell hit Bonus appears to be 3% too high. Elemental precision talent was changed from hit to resist.

##

**Comment by Hoedown9270** [comment]
Bug description appears blank for me. 

Spell hit Bonus appears to be 3% too high. Elemental precision talent was changed from hit to resist.

**Comment by BreakBB** [comment]
Hey @Hoedown9270 The hit modifier of this talent was the same in Classic.

TBC
https://tbc.wowhead.com/spell=29438/elemental-precision

vs

Classic
https://classic.wowhead.com/spell=29438/elemental-precision

Very point of spell hit reduces the change your target resists your spell. So the 3 points you can put into Elemental Precision actually are 3 % hit. Ofc the talent only increases Hit for Frost and Fire spells, but these are also in TBC the important ones.
