### ISSUE TITLE
Ranged Hit% Calculated Incorrectly

### ISSUE THREAD

**Issue by promaori** [BreakBB/ExtendedCharacterStats#124]
## Bug description

The hit chance calculated by ExtendedCharacterStats does not reflect the hit chance showing in the character sheet. In the example below, I have 110 ranged hit rating which is 11% @ L60. The ECS sheet below states I have 14% hit.

## Screenshots

![image](https://user-images.githubusercontent.com/4338039/119760960-13058980-beff-11eb-9317-3729fe8f9c92.png)

## Version

ExtendedCharacterStats Version 2.8.4 - Burning Crusade Classic

**Comment by BreakBB** [comment]
I will look into this shortly and get a fix out before TBC release. Thank you very much for reporting this :+1:
