### ISSUE TITLE
Curseforge always shows Tomtom as "Modified"

### ISSUE THREAD

**Issue by puffybc** [BreakBB/ExtendedCharacterStats#125]
## Bug description

**Curseforge always shows Tomtom as "Modified"**

## Screenshots

**see attached**

## Version

**![2021-05-29 (1)](https://user-images.githubusercontent.com/85028326/120075921-4700bc00-c071-11eb-86b3-e5acc8d9515c.png)**

**Comment by BreakBB** [comment]
I guess you mean "Extended Character Stats", but the main problem lies on CurseForges side. I will still try to get a workaround out for this!

Thank you very much for the report.
