### ISSUE TITLE
Stormrage Set Bonus

### ISSUE THREAD

**Issue by Dunnder** [BreakBB/ExtendedCharacterStats#13]
## Bug description
MP5 (casting) bonus for Stormrage 3-set bonus is not yet implemented.

Using Reflection talent + 3-set bonus should add up to 30% of MP5 (Spirit)

Love this addon!

Version:  v2.1.4

**Comment by BreakBB** [comment]
@Dunnder Yeah right. The setbonus isn't implemented. Neither is the Priest bonus. Reflection is already calculated though
