### ISSUE TITLE
Wow Classic Era Bug.

### ISSUE THREAD

**Issue by alias86** [BreakBB/ExtendedCharacterStats#134]
Hey WowUp (And other Update Managers), when they are set to Classic Era Only.

The last working version appears to be 2.7.3 for Classic Era.

Please could you loot into this?
many thanks, great addon <3

**Comment by BreakBB** [comment]
Hey, I have no idea what the issue is with these Addon Managers.

On CurseForge you can see ECS is listed for 1.13.7 with multiple new version:

https://www.curseforge.com/wow/addons/extended-character-stats/files

I will try to reach out to one of the WowUp devs and see if he knows anything.
