### ISSUE TITLE
classic era last update (a month ago ?)

### ISSUE THREAD

**Issue by Max-Sherlocked** [BreakBB/ExtendedCharacterStats#135]
## Bug description

ECS doesnt work anymore on wow classic era, since i updated it after bc launch.

## Screenshots

![image](https://user-images.githubusercontent.com/34794290/123415322-5feb8700-d5b5-11eb-942b-02959196ec8c.png)

## Version
 
2.8.6 era

**Comment by Max-Sherlocked** [comment]
Gues whos back ? ECS on ERA ! ty a lot <3 
![image](https://user-images.githubusercontent.com/34794290/124207784-91e57780-dae6-11eb-97dc-5440f870ab96.png)

**Comment by BreakBB** [comment]
@Max-Sherlocked You are very welcome, thanks for using ECS 😃
