### ISSUE TITLE
Arcane Instability (crit rate) and Arcane Focus (arcane hit rate) aren't reflected in ECS

### ISSUE THREAD

**Issue by meatGUY** [BreakBB/ExtendedCharacterStats#14]
## Bug description
Arcane Instability (crit rate) and Arcane Focus (arcane hit rate) aren't reflected in ECS

## Version
v2.1.4

**Comment by BreakBB** [comment]
@meatGUY Thanks for the report. I think you're right that the Arcane Instability isn't reflected yet. Have to look into the Arcane Focus talent, but I think you're right with this as well. Should be easy to fix :+1:

**Comment by BreakBB** [comment]
@meatGUY I've added the Arcane Instability talent. For now I don't think the Arcane Focus talent is really useful. There're not much arcane spells and ECS currently doesn't list the hit rates by spell schools.
