### ISSUE TITLE
Spell hit rating does not account for socketed gems

### ISSUE THREAD

**Issue by turetafr** [BreakBB/ExtendedCharacterStats#140]
As stated, the add-on does not reflect socketed gems in the spell hit rating or bonus.

**Comment by BreakBB** [comment]
Hey @turetafr Thanks for the hint, I will have to look into this to check what I can do about it 👍🏻

**Comment by RickTee** [comment]
As far as I can tell spell hit is completely wrong. I have 202 spell hit rating wow interface shows this to be 16.01% but this addon says it's 26%.

**Comment by BreakBB** [comment]
@RickTee What class and spec do you play? And could you share some screenshots of the wrong values?

**Comment by RickTee** [comment]
Warlock Affliction
![CharEcs](https://user-images.githubusercontent.com/17412261/134867995-892ee26d-ff62-4ca5-b98b-fa1a4f2ae2c8.jpg)
![CharHitStat](https://user-images.githubusercontent.com/17412261/134868007-f794e254-a51f-408a-8744-38b5b8f5d26c.jpg)
.

**Comment by BreakBB** [comment]
@RickTee And talents selected which reduces the hit cap you need?

**Comment by RickTee** [comment]
3 points in suppression, hmm first figures were from spec that had 5 points in suppression. Does that mean each point in suppression gives 2 points of hit but only to affliction spells? The spell hit in the addon would then not apply to destruction spells? or am I as confused as ever.
