### ISSUE TITLE
Shaman Dual-Wield Specialization talent is not being applied to hit %

### ISSUE THREAD

**Issue by mattlokk** [BreakBB/ExtendedCharacterStats#141]
![image](https://user-images.githubusercontent.com/3373299/124184113-f6b0bb80-da6d-11eb-87ca-97397b628edf.png)

getting the 3% from my Nature's Guidance talent, but not the 6% from Dual-Wield Specialization

**Comment by mattlokk** [comment]
after the update it now shows 6% hit. It should show 9% with both talents maxed.

**Comment by BreakBB** [comment]
Thanks for reporting again @mattlokk I will have to have another look at this as it seems 🤔
