### ISSUE TITLE
wrong variable causing namespace collision

### ISSUE THREAD

**Issue by orionshock** [BreakBB/ExtendedCharacterStats#144]
variable should be "bonus", not "mod"

using "mod" here introduced global name space collision with the Default UI and with Questie oddly enough.

https://github.com/BreakBB/ExtendedCharacterStats/blob/1abdca59a283de764f9e451b530f10c75eb381b9/Modules/Data/SpellHit.lua#L55

**Comment by orionshock** [comment]
mod is a default math function and this overwrites it...

**Comment by BreakBB** [comment]
@orionshock Sorry for the broken update v2.8.8 - I released a fixed version yesterday so make sure to update.
