### ISSUE TITLE
New Lua Error Message

### ISSUE THREAD

**Issue by AlucardNoir** [BreakBB/ExtendedCharacterStats#149]
Getting this error on login with any character... any ideas how to resolve this issue?

Message: ...\AddOns\ExtendedCharacterStats\Modules\GearInfos.lua:81: attempt to index field 'qualityTexture' (a nil value)
Time: Sun Jul 18 21:40:45 2021
Count: 1
Stack: ...\AddOns\ExtendedCharacterStats\Modules\GearInfos.lua:81: attempt to index field 'qualityTexture' (a nil value)
[string "@Interface\AddOns\ExtendedCharacterStats\ECS.lua"]:128: in function <Interface\AddOns\ExtendedCharacterStats\ECS.lua:124>
[string "@Interface\AddOns\ExtendedCharacterStats\ECS.lua"]:37: in function <Interface\AddOns\ExtendedCharacterStats\ECS.lua:30>

Locals: Stats = <table> {
 HideWindow = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Stats.lua:128
 UpdateInformation = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Stats.lua:302
 UpdateWindowSize = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Stats.lua:108
 RebuildStatInfos = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Stats.lua:289
 RecycleFrame = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Stats.lua:283
 GetFrame = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Stats.lua:137
 CreateWindow = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Stats.lua:40
 private = <table> {
 }
 UpdateSettingsButtonText = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Stats.lua:113
 GetDisplayedLines = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Stats.lua:142
 ToggleWindow = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Stats.lua:118
}
GearInfos = <table> {
 UpdateInspectGearColorFrames = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\GearInfos.lua:110
 Init = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\GearInfos.lua:28
 private = <table> {
 }
 ToggleColorFrames = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\GearInfos.lua:71
 UpdateGearColorFrames = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\GearInfos.lua:45
}
_RegisterEvents = <function> defined @Interface\AddOns\ExtendedCharacterStats\ECS.lua:168
lastSuccessfulSpellTime = 0

**Comment by BreakBB** [comment]
Hey @AlucardNoir I just released a new version here on GitHub and on CurseForge. That version fixes your issue and will be available soon on the regular addon managers.

Thanks for reporting this 👍🏻

**Comment by AlucardNoir** [comment]
Awesome! Thank you!
