### ISSUE TITLE
Incorrect melee/ranged miss chance calculation

### ISSUE THREAD

**Issue by dsvdmeer** [BreakBB/ExtendedCharacterStats#15]
## Bug description
The miss chance calculations for melee and ranged are incorrect. They assume use a miss chance against bosses of 8%, but it should be 9%.

## Cause
The function `_GetMissChanceByDifference()` in Data.lua uses the following formula: `6 + (defenseValue - weaponSkill - 10) * 0.4`. The 6 should be a 7.

## References
https://vanilla-wow.fandom.com/wiki/Hit
https://www.wowhead.com/news=292085/hit-cap-in-classic-wow-clarifications

## Version
I'm using version 2.1.4.

**Comment by BreakBB** [comment]
@dsvdmeer Thanks for your report. I will fix and release an update really soon. No idea why this hasn't been reported earlier :thinking:
