### ISSUE TITLE
Lock "Demonic Sacrifice" not handled correctly

### ISSUE THREAD

**Issue by bpevangelista** [BreakBB/ExtendedCharacterStats#151]
Under "Shadow Damage", Lock's Demonic Sacrifice on Succubus (+15% Shadow Damage) is not being accounted correctly.

Tested by looking at value before and after, and it's constant. Other things like Fel Armor are handled correctly.

**Comment by BreakBB** [comment]
Hey @bpevangelista

That is indeed correct! :O Will look into it and will try to push a release soon. Can't promise anything atm though 🙈
