### ISSUE TITLE
Lua error on settings

### ISSUE THREAD

**Issue by silverhawke249** [BreakBB/ExtendedCharacterStats#156]
## Bug description
Switching to Melee settings causes Lua error.

## Screenshots
```16x ...tendedCharacterStats\Modules\Config\MeleeSection.lua:66: attempt to index field 'expertise' (a nil value)
[string "@ExtendedCharacterStats\Modules\Config\MeleeSection.lua"]:66: in function `member'
```

## Version
TBC 2.8.11

**Comment by BreakBB** [comment]
Hey @silverhawke249 sorry for the late response. Could you run the following and report the output?

`/dump ExtendedCharacterStats.profile.melee.expertise`

If that is `nil` then try `/run ExtendedCharacterStats.general.profileVersion = 0` and do a `/reload`

**Comment by silverhawke249** [comment]
that fixes it, thanks!
(also unrelated but shouldn't this be "Quality"? :P)
![image](https://user-images.githubusercontent.com/50395934/134798824-97532135-9546-401f-81da-a50f03f7e398.png)

**Comment by BreakBB** [comment]
Hehe, I just found this typo yesterday while working on #155 😅 

It is kinda odd that some profile settings are not stored properly or something just get lost... Maybe I should add some more safety nets 🤔 

Thank for coming back to this @silverhawke249 Feel free to open up more issues if you find anything 👍🏻
