### ISSUE TITLE
Classic Era 1.14 Breaks 90% of addon

### ISSUE THREAD

**Issue by derastoby** [BreakBB/ExtendedCharacterStats#157]
## Bug description

Since 1.14 patch (in Classic ERA) addon still runs and window shows but Settings button does nothing and stats shown cannot be changed (and have forgotten previous settings).

## Version

Classic ERA 2.8.11-era

**Comment by BreakBB** [comment]
Hey @derastoby Thanks for letting me know. Once I have time for ECS again I will check that 🙈 Could you do me a favor and try the following:

`/run ExtendedCharacterStats.general.profileVersion = 0` and then do a `/reload`?

**Comment by derastoby** [comment]
Thanks for the help! :)
On reload I saw:
 "[ECS]: Migrating ECS profile version fro 0 to 10"
It has changed what's shown in the ECS window, now see a lot of melee stats - probably the same as the default setup.
I can scroll down them, but not right down to below the "Spell" line (unless all spell stats are turned off).
Settings button sadly still does not work.
Hope this help you a little in figuring it out.  ECS is much less broken than some other addons by the way, hopefully it easy to fix. :)

**Comment by BreakBB** [comment]
Yeah correct, your settings should be reset to default now. Do you have any error you could share @derastoby ?

I guess I should just test it myself and ship an update. Problem is that I currently are very limited in time 🙈 

For others reading this: Most likely some API function changed, which is now `nil` and therefore breaks ECS.

**Comment by derastoby** [comment]
I think you're bang on with the "nul" idea. :)

Error on opening character pane (with ECS turned on):
Message: ...face\AddOns\ExtendedCharacterStats\Modules\Stats.lua:56: attempt to index global 'ECSConfigFrame' (a nil value)
Time: Wed Oct  6 21:08:38 2021
Count: 1
Stack: ...face\AddOns\ExtendedCharacterStats\Modules\Stats.lua:56: attempt to index global 'ECSConfigFrame' (a nil value)
Locals: 

Error clicking Settings button:
Message: ...face\AddOns\ExtendedCharacterStats\Modules\Stats.lua:56: attempt to index global 'ECSConfigFrame' (a nil value)
Time: Wed Oct  6 21:11:20 2021
Count: 2
Stack: ...face\AddOns\ExtendedCharacterStats\Modules\Stats.lua:56: attempt to index global 'ECSConfigFrame' (a nil value)
Locals: 

Lots of the other errors, from other addons are also nil value related, mostly "attempt to call method 'SetBackdropBorderColor' (a nil value)" - in case this helps you at all.

**Comment by BreakBB** [comment]
Thanks for posting the error messages @derastoby 

Actually this is not really what I expected to be `nil` 😅 `ECSConfigFrame` is something that ECS creates using an external dependencies (AceGUI library). Not sure what is going on on the new PTR servers and the version used there.

Yeah I already read, that "all" Backdrop related APIs are gone with 1.14.1.

**Comment by derastoby** [comment]
also - although stats are shown, I've just noticed they do not change when swapping gear, etc - so maybe more is broken that I first though sadly.

**Comment by BreakBB** [comment]
Hey @derastoby would you mind testing this version. I was able to reproduce your error and I think I also found the issue:

[ExtendedCharacterStats-v2.8.11-era-913e4f9.zip](https://github.com/BreakBB/ExtendedCharacterStats/files/7357238/ExtendedCharacterStats-v2.8.11-era-913e4f9.zip)

**Comment by BreakBB** [comment]
@derastoby Thanks once again for reporting back on this issue 🙏🏻 

Could you tell me which class you are playing and show me your skill tree? That would be helpful to investigate what exactly is going on.

**Comment by derastoby** [comment]
You are very welcome - happy to help such a great addon/creator!
I play a Moonkin druid, so no talents that add to spell hit (sadly).
I did just try another stats addon and it appears to have exactly the same problem for Spell Hit, with the odd 7x multiplier -  although its +Crit appears to work and Boomkin form/aura only adds 3% crit.

Did you actually need a screenshot of my talent trees?  I have all the normal moonkin ones, so lots of +damage boosts and so on but no hit or crit (apart from Moonfire crit) - but can screenshot if you need.

**Comment by BreakBB** [comment]
Hey @derastoby sorry for not answering on this topic for so long. I've been pretty busy again 🙈 

Since you are playing moonkin AND also took the time to test other stat addons, I don't need a screenshot of your talent trees - thanks again for helping out on this.

I can't promise when I will have a solution for this, but I am onto it.

**Comment by BreakBB** [comment]
Could you run the following command and report the output?

`/dump GetSpellHitModifier()`

**Comment by derastoby** [comment]
Hi,
No problem on the delays (appreciate it's not your job to make the Addons of course) 🙂
I've run that and get:
[1]=70
back.  not sure what that is suggesting or if it help you at all.
Thank again.
________________________________

**Comment by BreakBB** [comment]
@derastoby that means the API thinks you have 70% hit, which matches with your report of ECS showing 70% hit in your raid gear.

Could you unequip all your hit gear and run that command again? And then with just one piece of hit gear?

For know it seems that there is an issue on Blizzards side. Alternatively the API changed, which I am unaware of at this point.

**Comment by BreakBB** [comment]
Also @derastoby could you try the following:

`/dump GetCombatRatingBonus(11)`

**Comment by derastoby** [comment]
Hi again and sorry it's taken so long!

I see there's a new version out via CurseForge but I had bad news I'm afraid.
The window shows and Settings button works OK, and the HIT values are now working well!
But all stats are not Colorized, even with the setting set, though they aren't white, kind of an off pink-grey when it is set.  The longer names, like movement speed are too wide for the window and the last character of 100% is cut off.
Also it reports loads of errors at logon and everytime it's opened or gear changed, like:
[ECS] ERROR The translation for <MOVEMENT_SPEED> is missing completely.  Please report this!

/dump GetCombatRatingBonus(11)
gives
[1]=0

/dump GetSpellHitModifier()
gives 0 with no +HIT gear on and 7 with a pice of +1 and 14 with a price of +2 gear equipped.

But you've fixed the +HIT in the AddOn now it seems - great job!  Was it the API?

Hope the above helps
all the best and thanks again.
Deras

________________________________
