### ISSUE TITLE
Error for Arcane mages Spell power calculation

### ISSUE THREAD

**Issue by Mishika08** [BreakBB/ExtendedCharacterStats#158]
For Arcane mages, spell power shown by the addon is always way higher than the value shown by the game UI (even naked).

![Error](https://user-images.githubusercontent.com/92177296/136597372-78cabc7a-ce86-4cad-a75a-d636e49b1914.png)

In the module "**SpellDamage.lua**" found in "........\ExtendedCharacterStats\Modules\Data", the spell power modifications from the talents Arcane instability and Mind Mastery are applied to the variable "spellDmg" defined as "**local spellDmg = GetSpellBonusDamage(school)**". It seems like the value originally stored in this variable is the final one, already affected by the talents. By applying the talents modification afterwards, it doubles their effect.

I tried removing the modifiers and the value shown in the addon was then the same as the game UI.

![Corrected](https://user-images.githubusercontent.com/92177296/136597447-bd7a94e0-dc24-4cae-8e81-837ba7ba09ca.png)

Simply defining the spell damage returned as "local spellDmg = GetSpellBonusDamage(school)" is sufficient.

**Comment by BreakBB** [comment]
Hey @Mishika08 that would be a big finding! I will try to verify this on the PTR, as soon I have time 👍🏻

**Comment by BreakBB** [comment]
Hey @Mishika08 sorry for the late response, but I finally found the time to look into this issue. Here are my results:

The calculation of the "Arcane Instability" bonus is working just fine. The default UI does not reflect the talent as you can see here:

With 0/3 Arcane Instability:
![grafik](https://user-images.githubusercontent.com/33514570/141841924-4c03852b-2673-45ee-ac0f-a7c6cec3e154.png)

With 3/3 Arcane Instability:
![grafik](https://user-images.githubusercontent.com/33514570/141841988-78fdc3a9-f16d-4897-ab22-4eb440b88c56.png)

Buuuuut, for Mind Mastery you are absolutly correct and the effect is already reflected in the default UI and as well in the API.

0/5 Mind Mastery:
![grafik](https://user-images.githubusercontent.com/33514570/141842143-027efa73-d125-47b2-b669-f09d587a82d1.png)

5/5 Mind Mastery:
![grafik](https://user-images.githubusercontent.com/33514570/141842306-78aec616-2b5b-419c-a389-03b3b5171caf.png)

A fix for the latter will be included in the next release. Thank you very much for reporting this 👍🏻

**Comment by Mishika08** [comment]
Hey ! Sorry I did not see your answer !

Pretty weird that the default UI reflects some of the talents but not all of them. At least you figured out the ones to be included =P

Glad it helped you !
