### ISSUE TITLE
MP5 Bug

### ISSUE THREAD

**Issue by Restomagus** [BreakBB/ExtendedCharacterStats#159]
![image](https://user-images.githubusercontent.com/54689086/139506859-0f7589af-db55-48a4-ba84-631b96458083.png)

![image](https://user-images.githubusercontent.com/54689086/139506887-f7c7fd59-1e02-43b9-8c97-738ad977bcd0.png)

Note in the 2 images above my supposed MP5 while casting (which is wrong) and also my lack of mana from spirit impacting MP5 while casting talent.

Note in the image below which version I am running

![image](https://user-images.githubusercontent.com/54689086/139506951-0167a504-1681-40a7-ba6a-2ba27b4cb7ce.png)

**Comment by BreakBB** [comment]
Hey @Restomagus thanks for the report.

This looks indeed like a problem and I already found something not so related to this. in TBC the Meditation talent moved from place 8 to place 9, which is not correctly handled yet.

I will look into it more deeply.

As a small help from you it would be great if you could run the followin command and report the outcome:

`/dump GetManaRegen()`

**Comment by Restomagus** [comment]
I cannot recall which character I noticed an MP5 issue on, I am seeing this
email 2 weeks late oops.

Tested on this toon:

[image: image.png]

**Comment by Restomagus** [comment]
I went looking more and see a problem on my priest:

[image: image.png]

**Comment by Restomagus** [comment]
On the priest:

[image: image.png]

**Comment by BreakBB** [comment]
Hey @Restomagus unfortunately I am not able to see any of the images you sent. Would be great if you could try again to attach them to your posts 😁

**Comment by BreakBB** [comment]
Nope, still nothing @Restomagus
I guess you have to log in into either the GitHub App or web version to attach images 🙈

**Comment by Restomagus** [comment]
in the most recent one I attached the image as a .JPG

**Comment by Restomagus** [comment]
Wait ....

" I guess you have to log in into either the GitHub App or web version to
attach images 🙈"

I am literally replying in my email and sending pictures,through my gmail
account. Do I need to go to a website for you?

**Comment by BreakBB** [comment]
In order to attach pictures visit https://github.com/BreakBB/ExtendedCharacterStats/issues/159 which is the issue you created a while back 😅

**Comment by BreakBB** [comment]
Well I think I found the issue. Needs some more testing though.

**Comment by Restomagus** [comment]
![image](https://user-images.githubusercontent.com/54689086/142718088-8619b9b1-ed82-48f8-9b0e-46876c7fda47.png)

**Comment by Restomagus** [comment]
![image](https://user-images.githubusercontent.com/54689086/142718128-b7a6fbed-7a8d-42bf-ae47-46a6c211e086.png)


![image](https://user-images.githubusercontent.com/54689086/142718136-505fcdcd-5ced-40a3-b7d3-6660f680b150.png)


These are images of his stats for other info incase you need that to go with the text box info
