### ISSUE TITLE
Flying movement speed updating

### ISSUE THREAD

**Issue by Iowerth** [BreakBB/ExtendedCharacterStats#160]
## Bug description
Flying movement speed (next - MS) updates only when uncheck/check flag in settings. Steps to reproduce:
1. Open character window. Char on feet. MS = 108%
![1](https://user-images.githubusercontent.com/10152411/139527365-ba3b783d-077a-4a9d-af07-ed4f73a30027.jpg)
2. Use fly mount. MS = 220%
![2](https://user-images.githubusercontent.com/10152411/139527399-daf641a3-fdc9-4e3b-99ef-a3b311840808.jpg)
3. Go to skies. MS still 220%
4. Go to addon settings. Uncheck/check flag. MS = 418%
![3](https://user-images.githubusercontent.com/10152411/139527453-d49ab2fd-e47a-4e96-95c0-48bc7e7d0599.jpg)

## Version
2.8.11

**Comment by BreakBB** [comment]
Hey @Iowerth yeah that is a known issue and a limitation to the API unfortunately. I haven't found a clean way to update this with reasonable performance.

But I will keep this open to have another look at some point.

**Comment by BreakBB** [comment]
Closing this in favor of #193
