### ISSUE TITLE
ERROR SPAM v2.9.0-tbc

### ISSUE THREAD

**Issue by ronin784** [BreakBB/ExtendedCharacterStats#163]
## Bug description

Error spam in WoW chat

## Screenshots

[ECS] ERROR The translation for <Holy Crit> is missing completely. Please report this!
[ECS] ERROR The translation for <Physical Damage> is missing completely. Please report this!
[ECS] ERROR The translation for <Shadow Crit> is missing completely. Please report this!
[ECS] ERROR The translation for <Arcane Damage> is missing completely. Please report this!
[ECS] ERROR The translation for <Nature Crit> is missing completely. Please report this!
[ECS] ERROR The translation for <Penetration> is missing completely. Please report this!
[ECS] ERROR The translation for <Miss (Lvl + 3)> is missing completely. Please report this!
[ECS] ERROR The translation for <Miss> is missing completely. Please report this!
[ECS] ERROR The translation for <Rating> is missing completely. Please report this!
[ECS] ERROR The translation for <Bonus> is missing completely. Please report this!
[ECS] ERROR The translation for <Crit Chance> is missing completely. Please report this!
[ECS] ERROR The translation for <MP5 (Buffs)> is missing completely. Please report this!
[ECS] ERROR The translation for <MP5 (Spirit)> is missing completely. Please report this!
[ECS] ERROR The translation for <MP5 (Casting)> is missing completely. Please report this!
[ECS] ERROR The translation for <MP5 (Items)> is missing completely. Please report this!
[ECS] ERROR The translation for <Attack Power> is missing completely. Please report this!
[ECS] ERROR The translation for <Expertise> is missing completely. Please report this!
[ECS] ERROR The translation for <Off Hand> is missing completely. Please report this!
[ECS] ERROR The translation for <Main Hand> is missing completely. Please report this!
[ECS] ERROR The translation for <Miss (Lvl + 3)> is missing completely. Please report this!
[ECS] ERROR The translation for <Miss> is missing completely. Please report this!
[ECS] ERROR The translation for <Rating> is missing completely. Please report this!
[ECS] ERROR The translation for <Bonus> is missing completely. Please report this!
[ECS] ERROR The translation for <Crit Chance> is missing completely. Please report this!
[ECS] ERROR The translation for <Attack Power> is missing completely. Please report this!
[ECS] ERROR The translation for <Attack Speed> is missing completely. Please report this!
[ECS] ERROR The translation for <Miss (Lvl + 3)> is missing completely. Please report this!
[ECS] ERROR The translation for <Miss> is missing completely. Please report this!
[ECS] ERROR The translation for <Rating> is missing completely. Please report this!
[ECS] ERROR The translation for <Bonus> is missing completely. Please report this!
[ECS] ERROR The translation for <Crit Chance> is missing completely. Please report this!
[ECS] ERROR The translation for <Crit Immune> is missing completely. Please report this!
[ECS] ERROR The translation for <Defense> is missing completely. Please report this!
[ECS] ERROR The translation for <Block Chance> is missing completely. Please report this!
[ECS] ERROR The translation for <Parry Chance> is missing completely. Please report this!
[ECS] ERROR The translation for <Resilience> is missing completely. Please report this!
[ECS] ERROR The translation for <Crit Reduction> is missing completely. Please report this!
[ECS] ERROR The translation for <Armor> is missing completely. Please report this!
[ECS] ERROR The translation for <Dodge Chance> is missing completely. Please report this!
[ECS] ERROR The translation for <Defense Rating> is missing completely. Please report this!
[ECS] ERROR The translation for <Block Value> is missing completely. Please report this!
[ECS] ERROR The translation for <Movement Speed> is missing completely. Please report this!
[ECS] ERROR The translation for <Physical Crit> is missing completely. Please report this!
[ECS] ERROR The translation for <Arcane Crit> is missing completely. Please report this!
[ECS] ERROR The translation for <Nature Damage> is missing completely. Please report this!
[ECS] ERROR The translation for <Holy Damage> is missing completely. Please report this!
[ECS] ERROR The translation for <Frost Crit> is missing completely. Please report this!
[ECS] ERROR The translation for <Fire Damage> is missing completely. Please report this!
[ECS] ERROR The translation for <Healing Power> is missing completely. Please report this!
[ECS] ERROR The translation for <Fire Crit> is missing completely. Please report this!
[ECS] ERROR The translation for <Shadow Damage> is missing completely. Please report this!
[ECS] ERROR The translation for <Frost Damage> is missing completely. Please report this!
[ECS] ERROR The translation for <Holy Crit> is missing completely. Please report this!
[ECS] ERROR The translation for <Physical Damage> is missing completely. Please report this!
[ECS] ERROR The translation for <Shadow Crit> is missing completely. Please report this!
[ECS] ERROR The translation for <Arcane Damage> is missing completely. Please report this!
[ECS] ERROR The translation for <Nature Crit> is missing completely. Please report this!
[ECS] ERROR The translation for <Penetration> is missing completely. Please report this!
[ECS] ERROR The translation for <Miss (Lvl + 3)> is missing completely. Please report this!
[ECS] ERROR The translation for <Miss> is missing completely. Please report this!
[ECS] ERROR The translation for <Rating> is missing completely. Please report this!
[ECS] ERROR The translation for <Bonus> is missing completely. Please report this!
[ECS] ERROR The translation for <Crit Chance> is missing completely. Please report this!
[ECS] ERROR The translation for <MP5 (Buffs)> is missing completely. Please report this!
[ECS] ERROR The translation for <MP5 (Spirit)> is missing completely. Please report this!
[ECS] ERROR The translation for <MP5 (Casting)> is missing completely. Please report this!
[ECS] ERROR The translation for <MP5 (Items)> is missing completely. Please report this!
[ECS] ERROR The translation for <Attack Power> is missing completely. Please report this!
[ECS] ERROR The translation for <Expertise> is missing completely. Please report this!
[ECS] ERROR The translation for <Off Hand> is missing completely. Please report this!
[ECS] ERROR The translation for <Main Hand> is missing completely. Please report this!
[ECS] ERROR The translation for <Miss (Lvl + 3)> is missing completely. Please report this!
[ECS] ERROR The translation for <Miss> is missing completely. Please report this!
[ECS] ERROR The translation for <Rating> is missing completely. Please report this!
[ECS] ERROR The translation for <Bonus> is missing completely. Please report this!
[ECS] ERROR The translation for <Crit Chance> is missing completely. Please report this!
[ECS] ERROR The translation for <Attack Power> is missing completely. Please report this!
[ECS] ERROR The translation for <Attack Speed> is missing completely. Please report this!
[ECS] ERROR The translation for <Miss (Lvl + 3)> is missing completely. Please report this!
[ECS] ERROR The translation for <Miss> is missing completely. Please report this!
[ECS] ERROR The translation for <Rating> is missing completely. Please report this!
[ECS] ERROR The translation for <Bonus> is missing completely. Please report this!
[ECS] ERROR The translation for <Crit Chance> is missing completely. Please report this!
[ECS] ERROR The translation for <Crit Immune> is missing completely. Please report this!
[ECS] ERROR The translation for <Defense> is missing completely. Please report this!
[ECS] ERROR The translation for <Block Chance> is missing completely. Please report this!
[ECS] ERROR The translation for <Parry Chance> is missing completely. Please report this!
[ECS] ERROR The translation for <Resilience> is missing completely. Please report this!
[ECS] ERROR The translation for <Crit Reduction> is missing completely. Please report this!
[ECS] ERROR The translation for <Armor> is missing completely. Please report this!
[ECS] ERROR The translation for <Dodge Chance> is missing completely. Please report this!
[ECS] ERROR The translation for <Defense Rating> is missing completely. Please report this!
[ECS] ERROR The translation for <Block Value> is missing completely. Please report this!
[ECS] ERROR The translation for <Movement Speed> is missing completely. Please report this!
[ECS] ERROR The translation for <Physical Crit> is missing completely. Please report this!
[ECS] ERROR The translation for <Arcane Crit> is missing completely. Please report this!
[ECS] ERROR The translation for <Nature Damage> is missing completely. Please report this!
[ECS] ERROR The translation for <Holy Damage> is missing completely. Please report this!
[ECS] ERROR The translation for <Frost Crit> is missing completely. Please report this!
[ECS] ERROR The translation for <Fire Damage> is missing completely. Please report this!
[ECS] ERROR The translation for <Healing Power> is missing completely. Please report this!
[ECS] ERROR The translation for <Fire Crit> is missing completely. Please report this!
[ECS] ERROR The translation for <Shadow Damage> is missing completely. Please report this!
[ECS] ERROR The translation for <Frost Damage> is missing completely. Please report this!
[ECS] ERROR The translation for <Holy Crit> is missing completely. Please report this!
[ECS] ERROR The translation for <Physical Damage> is missing completely. Please report this!
[ECS] ERROR The translation for <Shadow Crit> is missing completely. Please report this!
[ECS] ERROR The translation for <Arcane Damage> is missing completely. Please report this!
[ECS] ERROR The translation for <Nature Crit> is missing completely. Please report this!
[ECS] ERROR The translation for <Penetration> is missing completely. Please report this!
[ECS] ERROR The translation for <Miss (Lvl + 3)> is missing completely. Please report this!
[ECS] ERROR The translation for <Miss> is missing completely. Please report this!
[ECS] ERROR The translation for <Rating> is missing completely. Please report this!
[ECS] ERROR The translation for <Bonus> is missing completely. Please report this!
[ECS] ERROR The translation for <Crit Chance> is missing completely. Please report this!
[ECS] ERROR The translation for <MP5 (Buffs)> is missing completely. Please report this!
[ECS] ERROR The translation for <MP5 (Spirit)> is missing completely. Please report this!
[ECS] ERROR The translation for <MP5 (Casting)> is missing completely. Please report this!
[ECS] ERROR The translation for <MP5 (Items)> is missing completely. Please report this!
[ECS] ERROR The translation for <Attack Power> is missing completely. Please report this!
[ECS] ERROR The translation for <Expertise> is missing completely. Please report this!
[ECS] ERROR The translation for <Off Hand> is missing completely. Please report this!
[ECS] ERROR The translation for <Main Hand> is missing completely. Please report this!
[ECS] ERROR The translation for <Miss (Lvl + 3)> is missing completely. Please report this!
[ECS] ERROR The translation for <Miss> is missing completely. Please report this!
[ECS] ERROR The translation for <Rating> is missing completely. Please report this!
[ECS] ERROR The translation for <Bonus> is missing completely. Please report this!
[ECS] ERROR The translation for <Crit Chance> is missing completely. Please report this!

**Comment by BreakBB** [comment]
Hey @ronin784 looks like the migration didn't work for you. Did you install some unofficial version before the last release? 🤔 

You can fix this by hitting "Reset ECS" in the Settings.

**Comment by QuantumImmortality** [comment]
There is no "Reset ECS' in the config brought up by `/ecs config`

**Comment by BreakBB** [comment]
@QuantumImmortality Then you are not using the newest version of ECS. The "General" section of the settings in v2.9.0 now has a reset button.

As an alternative you can give `/run ExtendedCharacterStats.general.profileVersion = 0` a try and do a `/reload` afterwards.

**Comment by ronin784** [comment]
> Hey @ronin784 looks like the migration didn't work for you. Did you install some unofficial version before the last release? 🤔
> 
> You can fix this by hitting "Reset ECS" in the Settings.

Sorry for the delay in responding, haven't played for a few days. I update my addons through CurseForge, i did a reinstall and the issue has been fixed, Nice to know about the reset button, thanks!

**Comment by BreakBB** [comment]
I am glad you got it fixed @ronin784 and thanks for coming back to respond. Feel free to open up a new issue if something else comes back up 👍🏻
