### ISSUE TITLE
Night Elf Feral Hit cap showing 6 instead of 5

### ISSUE THREAD

**Issue by Ashalkito** [BreakBB/ExtendedCharacterStats#170]
I'm playing Night Elf feral druid, and im confuse about the hit cap numbers the addon is showing up.
For hitting +0 levels enemies it says i need 6% hit to be fully capped. If i just go with 5% it shows 1% miss chance, but as far as i know you just need 5% bonus hit to avoid missing a +0 level enemy. 
Is this due to the addon taking in consideration I am Night Elf and it is taking me as the enemy reference, with the 1% dodge racial, or is it just a bug? Do i need to gear 6% hit to never miss in pvp scenarios supposing the enemy have flat 300 defense skill and no other bonus or am i fine with the 5%?

**Comment by BreakBB** [comment]
Hmmm... 🤔 

I am wondering why this never showed up before, but you are correct. The code currently starts with 6% hit cap when shape shifted and not 5% as it does when not shape shifted.

Thanks for opening the issue, I will make sure to fix it soon 👍🏻
