### ISSUE TITLE
Error in SpellHit.lua Line 97

### ISSUE THREAD

**Issue by Belden1** [BreakBB/ExtendedCharacterStats#172]
## Bug description

The error happend to me yesterday, I think after I died in raid and showed up as ghost...

## Version

v2.10.0 - WoW Classic SoM

---------

How I fixed it, maybe works or you can find better solution...?

	if GetSpellHitModifier() then
		return GetSpellHitModifier() / 7 -- For 1% hit on gear GetSpellHitModifier returns 7
	else
		return 0
	end

**Comment by BreakBB** [comment]
Hey @Belden1 do you have the full error message by chance? This is a blizzard API function which should always be available 🤔

**Comment by Belden1** [comment]
Tried it out now, happend to be after I got summoned into BRM...
But before I think it happend when I went into MC

`Message: ...Ons\ExtendedCharacterStats\Modules\Data\SpellHit.lua:97: attempt to perform arithmetic on a nil value
Time: Wed Jan 12 21:23:04 2022
Count: 1
Stack: ...Ons\ExtendedCharacterStats\Modules\Data\SpellHit.lua:97: attempt to perform arithmetic on a nil value
[string "@Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua"]:146: in function <...tCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:144>
[string "=[C]"]: ?
[string "@Interface\AddOns\ExtendedCharacterStats\Modules\Data\SpellHit.lua"]:97: in function `GetSpellHitBonus'
[string "@Interface\AddOns\ExtendedCharacterStats\Modules\Data\SpellHit.lua"]:30: in function <...Ons\ExtendedCharacterStats\Modules\Data\SpellHit.lua:26>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@Interface\AddOns\ExtendedCharacterStats\Modules\Stats.lua"]:167: in function <...face\AddOns\ExtendedCharacterStats\Modules\Stats.lua:165>
[string "@Interface\AddOns\ExtendedCharacterStats\Modules\Stats.lua"]:319: in function <...face\AddOns\ExtendedCharacterStats\Modules\Stats.lua:313>
[string "@Interface\AddOns\ExtendedCharacterStats\Modules\Stats.lua"]:306: in function `UpdateInformation'
[string "@Interface\AddOns\ExtendedCharacterStats\Modules\Init.lua"]:51: in function <...rface\AddOns\ExtendedCharacterStats\Modules\Init.lua:50>

Locals: private = <table> {
 ThrowError = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:46
 DoesErrorExist = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:87
 ClearOldErrors = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:107
 SanitizeLine = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:83
 MAX_STACK_DEPTH = 10
 log = <table> {
 }
 ErrorHandler = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:116
 IncrementErrorCount = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:77
 NewError = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:50
 IsRCLootCouncilError = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:94
}
orig_errorhandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:296
`

**Comment by BreakBB** [comment]
Hey @Belden1 thanks a lot for coming back to this so quickly!

I now see the issue (even though this seems like an API bug, but one ECS should handle gracefully. I will try to get this fixed soon.
