### ISSUE TITLE
Error when clicking "Spell" on the "Stats" Tab of Settings

### ISSUE THREAD

**Issue by houlia** [BreakBB/ExtendedCharacterStats#178]
version 2.11.0, wow TBC classic

5x ...tendedCharacterStats\Modules\Config\SpellSection.lua:53: attempt to index field 'hasteRating' (a nil value)
[string "@ExtendedCharacterStats\Modules\Config\SpellSection.lua"]:53: in function `member'
[string "@Quartz\libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-82.lua"]:221: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:169>
[string "@Quartz\libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-82.lua"]:1206: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1121>
[string "@Quartz\libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-82.lua"]:1652: in function `FeedGroup'
[string "@Quartz\libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-82.lua"]:1577: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1561>
[string "=[C]"]: ?
[string "@Attune\Libs\AceGUI-3.0\AceGUI-3.0-41.lua"]:72: in function <Attune\Libs\AceGUI-3.0\AceGUI-3.0.lua:70>
[string "@Attune\Libs\AceGUI-3.0\AceGUI-3.0-41.lua"]:306: in function `Fire'
[string "@Attune\Libs\AceGUI-3.0-41\widgets\AceGUIContainer-TreeGroup.lua"]:512: in function `SetSelected'
[string "@Attune\Libs\AceGUI-3.0-41\widgets\AceGUIContainer-TreeGroup.lua"]:189: in function <...ibs\AceGUI-3.0\widgets\AceGUIContainer-TreeGroup.lua:185>

**Comment by BreakBB** [comment]
Hey @houlia can you try the following:

`/run ExtendedCharacterStats.general.profileVersion = 0` and then do a `/reload`? This will reset ECS

**Comment by BreakBB** [comment]
Hey @houlia did you get this to work again? You should also be able to use the "Reset ECS" button in the settings to fix this issue.
