### ISSUE TITLE
Errors on last build

### ISSUE THREAD

**Issue by Trouler** [BreakBB/ExtendedCharacterStats#179]
Still not seeing Haste values on my character.
Instead I am greeted with errors when I go to the Stats tab in Settings:

`5x ...tendedCharacterStats\Modules\Config\SpellSection.lua:53: attempt to index field 'hasteRating' (a nil value)
[string "@ExtendedCharacterStats\Modules\Config\SpellSection.lua"]:53: in function `member'
[string "@Quartz\libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-82.lua"]:221: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:169>
[string "@Quartz\libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-82.lua"]:1206: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1121>
[string "@Quartz\libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-82.lua"]:1652: in function `FeedGroup'
[string "@Quartz\libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-82.lua"]:1577: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1561>
[string "=[C]"]: ?
[string "@Atlas\Libs\AceGUI-3.0\AceGUI-3.0-41.lua"]:72: in function <Atlas\Libs\AceGUI-3.0\AceGUI-3.0.lua:70>
[string "@Atlas\Libs\AceGUI-3.0\AceGUI-3.0-41.lua"]:306: in function `Fire'
[string "@Atlas\Libs\AceGUI-3.0-41\widgets\AceGUIContainer-TreeGroup.lua"]:512: in function `SetSelected'
[string "@Atlas\Libs\AceGUI-3.0-41\widgets\AceGUIContainer-TreeGroup.lua"]:189: in function <...ibs\AceGUI-3.0\widgets\AceGUIContainer-TreeGroup.lua:185>`

`2x ...tendedCharacterStats\Modules\Config\RangeSection.lua:66: attempt to index field 'hasteRating' (a nil value)
[string "@ExtendedCharacterStats\Modules\Config\RangeSection.lua"]:66: in function `member'
[string "@Quartz\libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-82.lua"]:221: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:169>
[string "@Quartz\libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-82.lua"]:1206: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1121>
[string "@Quartz\libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-82.lua"]:1652: in function `FeedGroup'
[string "@Quartz\libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-82.lua"]:1577: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1561>
[string "=[C]"]: ?
[string "@Atlas\Libs\AceGUI-3.0\AceGUI-3.0-41.lua"]:72: in function <Atlas\Libs\AceGUI-3.0\AceGUI-3.0.lua:70>
[string "@Atlas\Libs\AceGUI-3.0\AceGUI-3.0-41.lua"]:306: in function `Fire'
[string "@Atlas\Libs\AceGUI-3.0-41\widgets\AceGUIContainer-TreeGroup.lua"]:512: in function `SetSelected'
[string "@Atlas\Libs\AceGUI-3.0-41\widgets\AceGUIContainer-TreeGroup.lua"]:189: in function <...ibs\AceGUI-3.0\widgets\AceGUIContainer-TreeGroup.lua:185>`

`3x ...tendedCharacterStats\Modules\Config\MeleeSection.lua:98: attempt to index field 'hasteRating' (a nil value)
[string "@ExtendedCharacterStats\Modules\Config\MeleeSection.lua"]:98: in function `member'
[string "@Quartz\libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-82.lua"]:221: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:169>
[string "@Quartz\libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-82.lua"]:1206: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1121>
[string "@Quartz\libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-82.lua"]:1652: in function `FeedGroup'
[string "@Quartz\libs\AceConfig-3.0-3\AceConfigDialog-3.0\AceConfigDialog-3.0-82.lua"]:1577: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:1561>
[string "=[C]"]: ?
[string "@Atlas\Libs\AceGUI-3.0\AceGUI-3.0-41.lua"]:72: in function <Atlas\Libs\AceGUI-3.0\AceGUI-3.0.lua:70>
[string "@Atlas\Libs\AceGUI-3.0\AceGUI-3.0-41.lua"]:306: in function `Fire'
[string "@Atlas\Libs\AceGUI-3.0-41\widgets\AceGUIContainer-TreeGroup.lua"]:512: in function `SetSelected'
[string "@Atlas\Libs\AceGUI-3.0-41\widgets\AceGUIContainer-TreeGroup.lua"]:189: in function <...ibs\AceGUI-3.0\widgets\AceGUIContainer-TreeGroup.lua:185>`

**Comment by BreakBB** [comment]
Hey @Trouler this is on TBC or SoM? 🤔 

You can try the following: 

`/run ExtendedCharacterStats.general.profileVersion = 0` and then do a `/reload`? This will reset ECS

**Comment by Trouler** [comment]
It's TBC. Resetting seem to have fixed it. Thanks!
I tried just reinstalling it through Wowup yesterday, but I guess a reinstall doesn't clear settings.
