### ISSUE TITLE
Include Priest Holy Crit chance from talents

### ISSUE THREAD

**Issue by schichtmschacht** [BreakBB/ExtendedCharacterStats#18]
## Description
Hi, I believe that the increased critical chance for Holy spells in the Holy tree for Priests is not being added to the overall Holy crit chance found in the ECS. Could you take a look at that?

Best regards, Björn

**Comment by BreakBB** [comment]
@schichtmschacht Hey, sorry for the late response on this. So you mean the "Spell Bonus" section isn't showing the Holy-Crit correctly?

**Comment by schichtmschacht** [comment]
Hi, yes, that is correct. The critical strike chance should be above 10% with the talents included, but its only around 5 or 6%, coming from my Intellect stat only.

**Comment by BreakBB** [comment]
@schichtmschacht Thanks for your mail. Next time please just reopen the issue :) I'll attach the information you provided here.

> first of all I must thank you for the prompt action on the attempt to fix the issue. However I believe that the issue is still there. 
> 
> It shows (see screenshot) 8,26%, that includes the 5/8 bonus of T1, substract that and you get 6,26%. 
> 
> Without gear (see screenshot) I have 2,82% meaning that my gear gives me 3,44%. 
> 
> The 5% from talents do not factor into any of this. 
> 
> It should be 8,26% + 5% = 13,26%.

I just had a look at the code and already found the issue of this... With the latest release I added the calculation of the new crit value, but didn't use it 🤦‍♂ Sorry about it. I am planning to release a new version very soon.

## Screenshots

With gear
![image](https://user-images.githubusercontent.com/33514570/76243397-8b1f5b00-6238-11ea-9db6-a98cf08ea0a8.png)

Without gear
![image](https://user-images.githubusercontent.com/33514570/76243424-94102c80-6238-11ea-97cf-328491bd01e7.png)
