### ISSUE TITLE
the value when use  Demonic Sacrifice is not right

### ISSUE THREAD

**Issue by lifei1245** [BreakBB/ExtendedCharacterStats#185]
## Bug description
it shows correctly when i sacrifice succubus ,but when i sacrifice Imp, the value won't change

**Comment by BreakBB** [comment]
Hey @lifei1245 I also received a hint that the Demonic Sacrifice buff does not increase the Spell Power stat and therefore the buff should not be reflected in ECS. The next release will also remove the Shadow Damage change when sacrificing a Succubus.

Thank you very much for the report though 👍🏻
