### ISSUE TITLE
Armor Pen now showing correctly

### ISSUE THREAD

**Issue by NayooZ** [BreakBB/ExtendedCharacterStats#190]
Armor Pen not showing values correctly - see attached image.

1057 only shows 105

## Version 2.13.0

![image](https://user-images.githubusercontent.com/37068647/174480986-deca8a9b-f95e-43c9-be32-d431bbab6da0.png)

**Comment by BreakBB** [comment]
Hey @NayooZ go ahead and increase the width of your ECS window, that will fix the issue.

Just press the "Settings" button and increase the slider for "Window Width" a bit.

**Comment by NayooZ** [comment]
Oh my god. I've had ECS for this long and never realised there was the option for that! Thankyou.

**Comment by BreakBB** [comment]
You are very welcome @NayooZ I am glad it was such an easy fix 👍🏻
