### ISSUE TITLE
MP5 value (not casting) is specified without rounding

### ISSUE THREAD

**Issue by Mihail-D** [BreakBB/ExtendedCharacterStats#191]
## Bug description
MP5 value (not casting) is specified without rounding

## Screenshots
![WoWScrnShot_070922_205136](https://user-images.githubusercontent.com/11092701/178117331-a5286adb-ec04-469c-8ef2-759b3fcf1748.jpg)

## Version

2.13.2

**Comment by BreakBB** [comment]
Thanks for the report @Mihail-D 👍🏻 A fix will be out soon :)
