### ISSUE TITLE
Mount - Movement Speed Calculation Bug

### ISSUE THREAD

**Issue by boktai1000** [BreakBB/ExtendedCharacterStats#193]
## Bug description

https://www.curseforge.com/wow/addons/extended-character-stats?comment=382

Something seems to be wrong with the Headless Horseman's Night Charger when in comparison to my other toons as a baseline. Any time I freshly cast the mount while in Outland/anywhere I can use the Flying mount, it will display as Movement speed 200% or 220% depending if I have my Riding Crop equipped or not.

It seems like if I stay grounded and toggle my trinkets, it will toggle between 200% and 220% respectively, but if I engage the mount in flying it does not update until I toggle my trinkets or login/out of the game.

Item ID is 37012 - The Horseman's Reins - https://tbc.wowhead.com/item=37012/the-horsemans-reins

Spell ID is 48023 when used in Outlands (Flyable) - Headless Horseman's Night Charger is the name of the spell - https://tbc.wowhead.com/spell=48023/headless-horsemans-night-charger

Spell ID is 48024 when used in Azeroth/etc (Ground Only) - Headless Horseman's Mount is the name of the spell - https://tbc.wowhead.com/spell=48024/headless-horsemans-mount

Note: it is possible to get summoned to Outland while you have Spell ID 48024 and have the ground only version, which does require you to recast to get your mount to fly. There are some other obscure interactions that allow this such as finishing a PVP match queued in Outland while you are mounted, you will return to Outland on your ground mount spell ID and need to recast.

 

 

When I mount up fresh and check the Movement Speed, it lists as 220%.

## Screenshots

When I mount up fresh and check the Movement Speed, it lists as 220%.

![image](https://user-images.githubusercontent.com/9054563/185172615-556422e7-8cd8-4c10-9484-07f4828f23c0.png)

While mounted, if I logout and then login back to the same toon, it will display as 418%. Easy for me to replicate here. Another option is to toggle trinkets while the mount is flying to get it to update.

![image](https://user-images.githubusercontent.com/9054563/185172669-13cf6f9a-403d-40fe-af20-52fc780cffbf.png)

## Version

ExtendedCharacterStats-v3.0.1.zip

**Comment by BreakBB** [comment]
Hey @boktai1000 this is the same issue as with #160 Thanks for the report though.

The problem is, I haven't found a way yet to trigger an update of the stats once you lift off from the ground. If you are fast enough when mounting up and instantly lift off the speed is shown correctly.

I am currently pretty busy getting Questie ready for Wotlk and will try to look into ECS and required updates afterwards.

**Comment by BreakBB** [comment]
Yeah something like this would have to be added. Currently ECS simply grabs all the information off the Blizzard API whenever the player changes gear, changes gems, gets a buff or loses one @boktai1000 So there is no "calculating" needed as the API returns the current movement speed. So basically what ECS shows is correct, but simply not updated when you lift off with a flying mount.

**Comment by Galenthor** [comment]
this would suggest at least for me that this movement speed bug is not just for this mount, but all, since that is what I was going to report... fast flying mount, 300 riding skill should be what, 280%? on my game it's showing 380% for some reason...

**Comment by BreakBB** [comment]
Thanks for the hint @Galenthor , yes it is indeed not just for the Headless Horseman's Mount.

For the actual values: On a 280% mount you are actually moving at 380% speed, since the default (walking) is 100%.
