### ISSUE TITLE
enhancer shaman skilled hit rating tracked wrong maybe

### ISSUE THREAD

**Issue by Ryzom88** [BreakBB/ExtendedCharacterStats#194]
## Bug description

the hit i can skill in the enhancment tree might be tracked wrong.  If i skill 3/3 point into dual whield spec i should get 2% per one skillpoint, total 6% while holding two weapons each hand. 
so i stand here naked only with two one-handed mace and ECS show me only 2% total hit.  i dont know if its wrong from the addon or from the beta itself. 
in TBC it work properly, i tried the same, be naked two one-handed weapons only, it shows 6% as it should.

## Screenshots
![TBC Live](https://user-images.githubusercontent.com/112387262/187176184-c8bcb1b5-53c9-4b4d-8c1e-85e0362a0b9d.jpg)

![WotLk Beta](https://user-images.githubusercontent.com/112387262/187176213-4d38a6d5-d42f-4680-8d85-ec85e1ac3704.jpg)

## Version

ECS v3.0.1 WotLk Beta 3.4,0

ECS v3.0.1 TBCC Live 2.5.4

**Comment by BreakBB** [comment]
Hey @Ryzom88 this is indeed a bug (and there will be more most likely) as the talent trees changed with Wotlk and I didn't have the time yet to update ECS accordingly.

So currently ECS checks the wrong talents for this, sorry.

Once Questie is in a good shape, I'll invest some more time in ECS again.

**Comment by BreakBB** [comment]
Fixed in 85eed6dacfba8a5e6df89c8fcc65c9d74c82d343
