### ISSUE TITLE
prot paladin has too much hit in ecs 

### ISSUE THREAD

**Issue by djgreengod** [BreakBB/ExtendedCharacterStats#195]
## Bug description

ECS show 5% too much melee hit in bonus (10% with bonus) for a wotlk prepatch prot paladin. naked i still have 5%, in empty dual spec, seems correct. possible interaction with glyph of righteous defense? since no prot paladin talents give hit.

spec : https://www.wowhead.com/wotlk/talent-calc/paladin/-05005135200132311333310321-5023_001nma11nmh

## Screenshots

https://imgur.com/a/XJjZ3XQ

**Comment by BreakBB** [comment]
Hey @djgreengod yeah I have yet to go through all the talents for Wotlk... So there is most likely a lot of stuff not calculated correctly connected with talents.

I am still fixing Questie and will take my time for ECS afterwards, sorry.
