### ISSUE TITLE
Focused Aim - Hunter MM Talent 3% hit

### ISSUE THREAD

**Issue by Andreatti** [BreakBB/ExtendedCharacterStats#196]
## Bug description
The talent Focused Aim for MM hunters are not adding on Bonus Hit.
4.31% Bonus hit only display the HIT from 68 Hit Rating.

## Version
Version of ECS is V3.0.1 for Wrath Classic.

## Screenshots

![image](https://user-images.githubusercontent.com/9450279/188245318-eb8a1d7a-c062-4dd4-b0d4-309b0976fc61.png)

**Comment by Andreatti** [comment]
Hei, i update the addon today and see that change on hunter talent didnt work.
I dont know why, but the talent 3% its not adding on hit bonus.

**Comment by Andreatti** [comment]
> Hei, i update the addon today and see that change on hunter talent didnt work. I dont know why, but the talent 3% its not adding on hit bonus.

I see now that the new version of the addon is adding only on meele hit.
Ranged hit not working.

**Comment by BreakBB** [comment]
Argh, my bad @Andreatti sorry. I tried to get some easy fixes out yesterday 😅

**Comment by danny-zarko** [comment]
Go to ExtendedCharacterStats\Modules\Data\Ranged.lua

Go the function

function _Ranged:GetHitTalentBonus()

Add this to cover this talent

	local _, _, _, _, points, _, _, _ = GetTalentInfo(2, 27)
        bonus = points * 1 -- 0-3% Focus Aim
