### ISSUE TITLE
Latest version of the addon not actually compatible with Classic WotLK client

### ISSUE THREAD

**Issue by StereotypicalType** [BreakBB/ExtendedCharacterStats#197]
## Bug description

The addon is shown as being out of date for the latest version of the Classic TBC-> WotLK prepatch client.  The game sees it loaded, but only if "Load out of Date Addons" is checked.  When it's loaded, the interface of the addon is not shown, so it's effectively not working, event though compatibility with 3.4.0 client is indicated.

However, version 3.0.0 does load correctly.

## Version

v3.0.1

**Comment by BreakBB** [comment]
As you said yourself, if you simply check the "Load out of Date Addons" then the addons loads and works just fine.

But thanks for the hint, I will make sure to update the interface version soon, so it is not listed as "out of date" anymore.

**Comment by StereotypicalType** [comment]
Ah unfortunately as I said, even though the addon is loaded when "out of date" is checked--based on it being shown in the addon list while in-game--it's still not actually working for the 3.0.1 version.  I.e. its interface does not show up, even though it's supposed to be loaded.  But the 3.0.0 version does load correctly, including its interface that shows extra character stats.

**Comment by BreakBB** [comment]
Hey @StereotypicalType I just had another look, but couldn't find any issue. Is this still an issue for you or did you manage to fix it? Did you try to deactivate every addon except ECS and see if that helps?

**Comment by StereotypicalType** [comment]
> Hey @StereotypicalType I just had another look, but couldn't find any issue. Is this still an issue for you or did you manage to fix it? Did you try to deactivate every addon except ECS and see if that helps?

The latest version 3.0.2 loads correctly (as did 3.0.0).  By that I mean that there's the actual extra window showing extended character stats.  3.0.1 did not show that window interface, even when the game claimed the addon was loaded.  I'm now on the latest version 3.0.2 after using 3.0.0 (since 3.0.1 didn't work).
