### ISSUE TITLE
Haste + hit stats not shown properly - Incorrect WoW project ID check?

### ISSUE THREAD

**Issue by gewoonnico** [BreakBB/ExtendedCharacterStats#198]
## Bug description
In WotLK Classic, some stats are no longer shown. This is due to the 'IsTBC' check in code targeting the wrong project ID.

> ECS.IsTBC = WOW_PROJECT_ID == WOW_PROJECT_BURNING_CRUSADE_CLASSIC

This ID has been updated to `WOW_PROJECT_WRATH_CLASSIC` for WotLK. I'm unsure if there are others changes that need to be made, but fixing this check makes the stats show up again.

## Screenshots
![image](https://user-images.githubusercontent.com/2758065/188313255-17b3f730-377b-4897-962a-c75e0968297b.png)

## Version
v3.0.1 - WotLK Classic

**Comment by BreakBB** [comment]
Good point @gewoonnico Blizzard changed this quite some time into beta and I have yet to get ECS into a better shape 🙈 

I will try to get a fix out soon, sorry for the delay.
