### ISSUE TITLE
Protection paladin

### ISSUE THREAD

**Issue by Forthehorde2022** [BreakBB/ExtendedCharacterStats#199]
## Question
Can you confirm prot palladin's "touched by the light" talent ( increases spell power by 60% of your STR) is updating ECS stats correctly ?

**Comment by BreakBB** [comment]
No I can not at this point @Forthehorde2022 , sorry. I haven't had any time for ECS for the last weeks, because I am stick on updating Questie 🙈 I hope to have time for ECS soon :tm:
