### ISSUE TITLE
Addon's ECS button overrides equipment durability monitoring button

### ISSUE THREAD

**Issue by Mihail-D** [BreakBB/ExtendedCharacterStats#20]
This button is provided by Leatrix Plus (Classic) Addon.
https://www.curseforge.com/wow/addons/leatrix-plus-classic

Screenshot:
![image](https://user-images.githubusercontent.com/33514570/76626538-9bd21880-6539-11ea-9981-2abaf7dbbbbf.png)

**Comment by BreakBB** [comment]
@Mihail-D Thanks for the report! I will investigate and fix this shortly 👍
