### ISSUE TITLE
Incorrect miss chance used in hit calculation 

### ISSUE THREAD

**Issue by dasikora** [BreakBB/ExtendedCharacterStats#200]
## Bug description
Incorrect Miss chance is used in Hit calculation. Since prepatch, melee attacks against bosses have an 8% chance to miss baseline, not 9%. 

## Screenshots
![misschance](https://user-images.githubusercontent.com/37838866/189551465-1b09e2d6-a4e1-4585-b4aa-ac71cd7d40a4.JPG)

## Version
using version 3.0.1

**Comment by BreakBB** [comment]
Yeah you are absolute right, thanks for reporting @dasikora

ECS didn't receive any love in the last weeks, since I only have little time besides my real life and fixing Questie. I hope to at least get some small fixes into ECS soon!
