### ISSUE TITLE
Paladin Melee Hit fixed, spell hit still wrong.

### ISSUE THREAD

**Issue by LordOfOtakus** [BreakBB/ExtendedCharacterStats#201]
On the most recent version of ECS for Wrath, (3.0.2), Melee hit for Paladins was fixed (since the Precision talent no longer existed). Spell hit is still being given 5% extra hit, however.

Easiest fix is replacing line 53 in "SpellHit.lua" (which is "if classId == Data.PALADIN and ECS.IsWotlk then") with "if (not ECS.IsWotlk) and classId == Data.PALADIN then".

**Comment by BreakBB** [comment]
That is absolutely true, thanks for the hint! I did the release yesterday pretty fast and overlooked this point 🙈 Will be easy to fix (as you already said 👍🏻 )
