### ISSUE TITLE
Total Avoidance and Crit Reduction is incorrect.

### ISSUE THREAD

**Issue by LordOfOtakus** [BreakBB/ExtendedCharacterStats#206]
On the current version of ECS, the Avoidance % on ECS is .6% off of what it actually is.
After digging through Defense.lua and reading it, it appears its caused by "enemyAttackRating = (UnitLevel("player") + 3) * 5" on line 69. I can see why this was done, but its also inconsistent.

For every level above you that a monster is, your chance to be missed, dodged, blocked, or parried is reduced by 0.2%. So, for a boss, which is 3 levels above you, its each of those reduced by 0.6%. You changed the Miss to adjust for Bosses, but not the others.

For fixing this, I would recommend just removing the +3 from that line. Most tanks (and Tanking WAs) consider avoidance cap as 102.4%, to consider the .6% reduction for all 4 of those stats. making them all fall in line under the assumption of your enemy being a boss would make it more confusing overall.

Also, this was difficult to figure out why, but Crit Reduction from Resilience is incorrect. I believe Wrath changed the crit reduction per point of Resilience. The best fix for this is to change line 44 in Defense.lua to "local critReducingFromResilience = GetCombatRatingBonus(15)" 15 is the combat rating number tied to the Resilience stat, and this has the advantage being more accurate at any level instead of calculation crit reduction per resilience at max level.

**Comment by BreakBB** [comment]
Hey @LordOfOtakus thanks a lot for taking such a detailed investigation of the tanking stats! I'll try to dig into it myself and push a fix for it as soon as I can <3
