### ISSUE TITLE
Shadow dmg doesn't fully show

### ISSUE THREAD

**Issue by DevineLykan** [BreakBB/ExtendedCharacterStats#21]
## Bug description
Since you made the new interface, the shadow damage figure only shows to two digit places. So shows 425 as 42, make the window size bigger.

## Screenshots
CBA to screenshot - Maybe test before you publish updates?

## Version
v2.3.0

**Comment by BreakBB** [comment]
@DevineLykan Thanks for your report and sorry for the late response on this.

You can be sure though that I am testing the addon in all conscience before releasing an update. But with limited time and just a few characters it might happen that something like this slips through.

I am planning to release an update very soon which will fix your issue.
