### ISSUE TITLE
Hit-Chance wrong for Frost DKs

### ISSUE THREAD

**Issue by BreakBB** [BreakBB/ExtendedCharacterStats#212]
## Version

v3.0.3

**Comment by ostjaevel** [comment]
Add this to Melee.lua on line 90 or so.
    if classId == Data.DEATHKNIGHT then
        local _, _, _, _, points, _, _, _ = GetTalentInfo(2, 16)
        mod = points * 1 -- 0-3% Nerves of Cold Steel
    end

This seems to have fixed it for me, I have no idea as to why 16 is Nerves of Cold Steel, but I'll leave that to Blizzard.

**Comment by BreakBB** [comment]
Hey @ostjaevel thanks for looking into this! I will add that code shortly 👍🏻 

WIth the move to Wotlk Blizzard seems to have simply added all "new" talents to the end, counting wise. It's really weird 🤷🏻‍♂️

**Comment by BreakBB** [comment]
Fixed in f722238988cf9fae1092beaed6bed5d852dfa6e2
