### ISSUE TITLE
Crit reduction % wrong at any level that is not 70

### ISSUE THREAD

**Issue by LordOfOtakus** [BreakBB/ExtendedCharacterStats#213]
Once you go above level 70, crit reduction in ECS is wrong because it's set specifically to lvl 70.

Can be fixed by changing "LEVEL_70_MAX_SKILL" on line 11 of Defense.lua to be set to "(UnitLevel("player")) * 5" instead of 350. This will scale it to any appropriate level. And maybe change the variable name too.

**Comment by LordOfOtakus** [comment]
Note: Not a perfect fix, its still off sometimes, but I think its due to base defense not being maxed? Not sure.

**Comment by harley-baker** [comment]
> Note: Not a perfect fix, its still off sometimes, but I think its due to base defense not being maxed? Not sure.
> 
> Edit: Might just not update properly when you level up until a UI reload, the above seems to work.

Could move the skill calculation into the immunity calculation on line 42 but this number is only really relevant at max level so it would be a waste of a calculation 90% of the time

**Comment by BreakBB** [comment]
Fixed in #217
