### ISSUE TITLE
Hide Panel upon opening Gear manager

### ISSUE THREAD

**Issue by dasikora** [BreakBB/ExtendedCharacterStats#214]
Currently, when opening gear manager with ECS panel open, the panel is infront of the gear sets, making it unusable (see picture)

Is there any way you could move the ECS panel to be behind the gear set manager tab, or perhaps just close ECS automatically upon opening the gear manager?

## Description

![image](https://user-images.githubusercontent.com/37838866/193430882-af2f5ac8-a6a8-4c91-9a2b-7b408958c3a8.png)

**Comment by BreakBB** [comment]
Hey @dasikora that is a good idea and should be adressed. I can't promise when I will have enough time for this, since I am still working on getting Questie in a better shape.

**Comment by wheezy1749** [comment]
A simple addition of

```mainFrame:SetFrameLevel(0)```

Makes the equipment manager have a higher layer at least and makes it useable while the ECS frame is open. Might be a good workaround for the time being. At least have the ESC frame in the background.
