### ISSUE TITLE
Crit Reduction is 2% higher than it should be

### ISSUE THREAD

**Issue by TheTravellingSalesman** [BreakBB/ExtendedCharacterStats#218]
## Bug description

Under `Defense` in ECS v3.0.3, the Crit Reduction% is 2% higher than actual.

This is verified by hovering the blizz-provided tooltip. 

## Screenshots

![image](https://user-images.githubusercontent.com/36421850/194416685-41272fca-9ba6-4ede-89ac-94416d8d35c7.png)
Note that my Resilience is 0.
![image](https://user-images.githubusercontent.com/36421850/194416903-d359e607-813c-4c06-892b-236da7a41a37.png)

![image](https://user-images.githubusercontent.com/36421850/194416818-faf5ad7c-395b-4bb5-9dea-0e8ed65cce11.png)

## Version

ECS v3.0.3

**Comment by mattk926** [comment]
Seeing similar issues with how crit immunity is calculated.

**Comment by JacksonVox** [comment]
Avoidance is also off.

**Comment by jacobbndr** [comment]
If you go into ...interface\AddOns\ExtendedCharacterStats\Modules\Data\Defense.lua  and update the hardcoded local variable LEVEL_70_MAX_SKILL from 350 to 400 it seems to fix the issue.

**Comment by BreakBB** [comment]
This was adressed in #217 and a release will be out shortly :)
