### ISSUE TITLE
default defense is 0 on korean client 

### ISSUE THREAD

**Issue by echoi92** [BreakBB/ExtendedCharacterStats#219]
On Korean client shows 0 + 135 = 135 defense whereas if I change language to english is properly shows 400 + 135 = 535,

kr
![image](https://user-images.githubusercontent.com/6448634/194430023-541f0c76-fed5-4fcd-896c-d4f62f517a5e.png)
en
![image](https://user-images.githubusercontent.com/6448634/194430429-e5f30102-0e74-4c14-b7c7-84a88d06cb2a.png)

**Comment by echoi92** [comment]
Any reason we can't just use 
```
UnitDefense("player")
```

instead of this long block

```
    for i = 1, MAX_SKILL_LINES do
        local skillName, isHeader, _, rank, _, modifier  = GetSkillLineInfo(i)
        if (not skillName) then
            -- We exceeded the available skill lines
            break
        end

        if (not isHeader) and (skillName == DEFENSE) then
            skillRank = rank
            skillModifier = modifier
            break
        end
    end

    if ECS.IsWotlk then
        skillModifier = skillModifier + math.floor(GetCombatRatingBonus(CR_DEFENSE_SKILL))
    end
```

on defense.lua?

**Comment by BreakBB** [comment]
Hey @echoi92 iirc there was an issue on SoM with `UnitDefense` but I might be mistaken 🤔 

I'll look into it, thanks for pointing it out!
