### ISSUE TITLE
Spellcrit Calculation

### ISSUE THREAD

**Issue by realAnticheater** [BreakBB/ExtendedCharacterStats#22]
LVL 60 Dwarf Holypriest
Naked 119 Int = would be 2,01 Spellcrit (119/59,2) but ECS showing 2,8% spellcrit.

Why? Where does this 0,8% Critchance come from?

BR Anticheater

**Comment by BreakBB** [comment]
@realAnticheater Sorry for taking so long to answer on this. Actually I am using the [GetSpellCritChance](https://wow.gamepedia.com/API_GetSpellCritChance) API function to determine the spell crit chance. So the value shown is actually the value used/returned by Blizzard.

**Comment by woodyj13** [comment]
I'm not seeing the crit % from Benediction added into the total.

**Comment by BreakBB** [comment]
@realAnticheater I can't find any problem on my side, even at a second glance. The values returned by the API function named above are the values shown in ECS.

@woodyj13 Could you share a screenshot for this? I can't believe a single item isn't working while others are.

**Comment by helvexis** [comment]
![no benediction](https://user-images.githubusercontent.com/65888617/82788203-9169be80-9e9a-11ea-89e5-ae12a959b547.png)
![With bene](https://user-images.githubusercontent.com/65888617/82788210-94fd4580-9e9a-11ea-96e7-a73a18669f75.png)

Here we go the Crit chance for the benediction being added is from the int not the 2% holy crit that is on the piece. Also side note the mp5 from nightfin soup isnt showing up at all either

**Comment by BreakBB** [comment]
@helvexis Thank you very much for sharing those screenshots :pray: Actually I am using the Blizzard API for those values and now I wonder if Blizzard themselfs are calculating those values correct... :Thinking: I will try to reach out to them (even though I have little hope about a soon response) and also try to adjust the shown values accordingly.

For consumables I have already been notified about the Mageblood Potion and will also check the Nightfin Soup.

**Comment by BreakBB** [comment]
@helvexis Could you run the following command ingame with Benediction equiped and without it. Also report the output here?

`/dump GetSpellCritChance(2)`

**Comment by helvexis** [comment]
Ive picked up ZG buff but i will edit it after i lose it
13.034399986267 without benediction
13.639200210571 with benediciton

**Comment by BreakBB** [comment]
@helvexis That prooves my assumption, that the API function doesn't return the correct values >_> I will try to reach out to Blizzard and see if I can get any insight information about it.
