### ISSUE TITLE
DK Defence english

### ISSUE THREAD

**Issue by za-x-az** [BreakBB/ExtendedCharacterStats#220]
## Bug description

Defense is way off compared to the default interface.
lists the right numbers but clearly don't use then to add up the defense rating.
387+140 = 527 not 489

## Screenshots

https://imgur.com/a/jl6SPfr

## Version

V3.0.3

**Comment by BreakBB** [comment]
I see, well I can do that, sure 😁

**Comment by BreakBB** [comment]
Fixed in 4d4a37d771fde53e88edf872481648753f650348
