### ISSUE TITLE
Draenei Shamans are not getting their own Heroic Presence

### ISSUE THREAD

**Issue by BreakBB** [BreakBB/ExtendedCharacterStats#222]
## Bug description

A quick search showed, that Wotlk introduced [a new spell ID](https://www.wowhead.com/wotlk/spell=28878/heroic-presence) for Heroic Presence. It might be this is now needed for certain classes together with [the old ID](https://www.wowhead.com/wotlk/spell=6562/heroic-presence). 

## Version

v3.0.4

**Comment by ostjaevel** [comment]
Simple fix for this is to add this to line 109 in Melee.lua:
if (not otherDraeneiInGroup) and IsSpellKnown(6562) **_or IsSpellKnown(28878)_** then

And on line 134 in SpellHit.lua:
if (not otherDraeneiInGroup) and IsSpellKnown(28878) **_or IsSpellKnown(6562)_** then

Not sure if the best fix, but it adds the Draenei hit to both SpellHit and MeleeHit and not just the one that is "base" for the respective class. (ie shamans would only get spellhit and not melee hit, now they would get both.)

**Comment by BreakBB** [comment]
Thanks @ostjaevel 👍🏻
