### ISSUE TITLE
Enhancer shaman crit calculation wrong, thundering strikes not added crit to spells

### ISSUE THREAD

**Issue by Ryzom88** [BreakBB/ExtendedCharacterStats#226]
## Bug description

As the titel says. ECS dont track the crit for spells from thundering strikes. 

## Screenshots

![Unbenannt](https://user-images.githubusercontent.com/112387262/197296971-58fd2309-ba35-426a-9bae-057ffcb1129e.PNG)

## Version

v.3.0.4 WotlK Classic

**Comment by BreakBB** [comment]
Thanks for reporting this @Ryzom88 the next release will contain a fix 👍🏻
