### ISSUE TITLE
Latest 3.0.6 does not show item sets in the equipment manager

### ISSUE THREAD

**Issue by capSAR273** [BreakBB/ExtendedCharacterStats#228]
## Bug description
With ECS enabled, the equipment manager is empty of all item sets that were previously saved. Disabling the addon brings the saved item sets back.

## Screenshots
With ECS Disabled:
![image](https://user-images.githubusercontent.com/5252505/197423752-2a85a708-5742-4c4f-a3fb-0d14892427d9.png)

With ECS Enabled:
![image](https://user-images.githubusercontent.com/5252505/197423788-de469c8a-88af-41a3-89b8-7e2129cb46ca.png)

## Version
3.0.6 WOTLK Classic

**Comment by BreakBB** [comment]
Hey @capSAR273 thanks for reporting this! I will look into it, where I did wrong 🙈
