### ISSUE TITLE
Increase size of status window or make it adjustable

### ISSUE THREAD

**Issue by sh977218** [BreakBB/ExtendedCharacterStats#23]
## Bug description
When I use other add that increase font size. The ECS window can not display all informations. 

## Screenshots
![image](https://user-images.githubusercontent.com/5692380/77861104-04c7ba80-71e1-11ea-939e-09d599b4be00.png)

## Version
ECS v2.2.1

**Comment by BreakBB** [comment]
@sh977218 Thanks for the report. Could you name the addon you are using to increase the font size? I think making the font size adjustable shouldn't be too hard.
