### ISSUE TITLE
[Protection Paladin] Avoidance Stat not true

### ISSUE THREAD

**Issue by Darhen** [BreakBB/ExtendedCharacterStats#230]
## Bug description
Heya ! 
I wanted to report that the Avoidance stat value seems a little bit off on the ECS panel.
It doesn't match with the value I get using the original macro from Tankspot (back in 2009), which is also the same value from EightyUpgrades.com 

The Macro used :
/run ChatFrame1:AddMessage(format("Unhittable at 102.4%% - you have %.2f%%", GetDodgeChance() + GetBlockChance() + GetParryChance() + 5 + 1/(0.0625 + 0.956/(GetCombatRating(CR_DEFENSE_SKILL)/4.91850*0.04))))

## Screenshots
![WoWScrnShot_110422_075602](https://user-images.githubusercontent.com/46900626/199969817-56f6821b-caaf-438f-8c64-55389499e28f.jpg)

Also here is a link to my EightyUpgrade Set simulation for comparison sake https://eightyupgrades.com/set/4UeJbuCGnQXbmUCRvrCVdK

## Version
Extended Character Stats v3.0.7

Thanks and keep up your good work !

**Comment by BreakBB** [comment]
Hey @Darhen thanks a lot for reporting this and sorry for not responding for so long. I will look into this and hope to find the issue soon :tm:

**Comment by BreakBB** [comment]
Also could you link me the place you found that macro or more information on it?

ECS is using a totally different (and more simple) formular:

> 5 + (((playerDefense) - enemyAttackRating) * 0.04) + GetDodgeChance() + GetParryChance() + GetBlockChance()

**Comment by Darhen** [comment]
Hey, I'm happy to help.

Sadly Tankspot.com is not accessible anymore as the site went down years ago... I remember finding this macro on a post from ownedcore.com
Here the link: [https://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-general/wow-ui-macros-talent-specs/208724-tanking-avoidance-macros.html]
What makes me curious about all this is in the first place is that **EightyUpgrade.com** _(which I use in theorycrafting)_ seems to use the same formula that I've given you as its avoidance value is strictly the same as the one I get with the macro in-game. 

I don't know much about the formula, my guess is that maybe the Ecs formula doesn't include the diminishing returns that comes as we stacks more Parry & Dodge % ? That could explain why the value seems off by 1.25% .

I reported this because I know that later in P3 on Anub'arak 25 heroic mode, one of the tanks (the "block-tank") must be avoidance capped in order to survive tanking the adds.  I don't know which one of the two formulas is the right one

Hope you'll find a way to be sure and to correct it (or me) if need be. 
Thanks!

**Comment by Darhen** [comment]
Here is another trusty link I found about the hit table in wow and their calculations. Hope it helps. 
Sadly many information about the maths behind it all has been lost with the deaths of site like Elitist jerks or Maintankadin as many discussion originated from there.
https://wow.allakhazam.com/wiki/hit_table_%28wow%29
