### ISSUE TITLE
3.1.0 broken on classic era

### ISSUE THREAD

**Issue by Azotorp** [BreakBB/ExtendedCharacterStats#237]
`Message: ...dOns\ExtendedCharacterStats\Modules\Data\Defense.lua:69: Usage: GetCombatRatingBonus(ratingIndex)
Time: Sun Jul 16 11:02:18 2023
Count: 1
Stack: ...dOns\ExtendedCharacterStats\Modules\Data\Defense.lua:69: Usage: GetCombatRatingBonus(ratingIndex)
[string "@Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua"]:146: in function <...tCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:144>
[string "=[tsm error check]"]:1: in main chunk
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `GetCombatRatingBonus'
[string "@Interface\AddOns\ExtendedCharacterStats\Modules\Data\Defense.lua"]:69: in function <...dOns\ExtendedCharacterStats\Modules\Data\Defense.lua:66>
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "@Interface\AddOns\ExtendedCharacterStats\Modules\Stats.lua"]:171: in function <...face\AddOns\ExtendedCharacterStats\Modules\Stats.lua:169>
[string "@Interface\AddOns\ExtendedCharacterStats\Modules\Stats.lua"]:163: in function <...face\AddOns\ExtendedCharacterStats\Modules\Stats.lua:152>
[string "@Interface\AddOns\ExtendedCharacterStats\Modules\Stats.lua"]:218: in function <...face\AddOns\ExtendedCharacterStats\Modules\Stats.lua:184>
[string "@Interface\AddOns\ExtendedCharacterStats\Modules\Stats.lua"]:104: in function `CreateWindow'
[string "@Interface\AddOns\ExtendedCharacterStats\Modules\Init.lua"]:31: in function `OnPlayerLogin'
[string "@Interface\AddOns\ExtendedCharacterStats\ECS.lua"]:22: in function <Interface\AddOns\ExtendedCharacterStats\ECS.lua:15>

Locals: private = <table> {
 ThrowError = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:46
 DoesErrorExist = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:87
 ClearOldErrors = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:107
 SanitizeLine = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:83
 MAX_STACK_DEPTH = 10
 log = <table> {
 }
 ErrorHandler = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:116
 IncrementErrorCount = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:77
 NewError = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:50
 IsRCLootCouncilError = <function> defined @Interface\AddOns\RCLootCouncil_Classic\RCLootCouncil\Core\ErrorHandler.lua:94
}
orig_errorhandler = <function> defined @Interface\SharedXML\SharedBasicControls.lua:355
`

**Comment by BreakBB** [comment]
Thanks for reporting this @Azotorp Looks like, I didn't thought about API on classic Era when updating the avoidance calculation 🙈
