### ISSUE TITLE
Addon Not Available on Only One Character

### ISSUE THREAD

**Issue by PapaBear138** [BreakBB/ExtendedCharacterStats#238]
Using ExtendedCharacterStats-v3.1.0. After the update on 07/16/23, I cannot click the "Settings" button on ECS on one character. Also on this character, my items no longer have the color icons.  Thank you.

![ECS](https://github.com/BreakBB/ExtendedCharacterStats/assets/42214594/abddaadc-91ba-45e2-9ce5-4dd32ab76e8c)

**Comment by BreakBB** [comment]
Hey @PapaBear138 can you run the following commands in the chat and see if that helps?

`/run ExtendedCharacterStats.general.profileVersion = 0`
`/reload`

**Comment by PapaBear138** [comment]
It did not, sorry.  But thank you.

**Comment by BreakBB** [comment]
Checkout the latest version @PapaBear138 which I pushed a few hours ago.

**Comment by BreakBB** [comment]
I am glad it's working again @PapaBear138 thanks for reporting back! Enjoy the game 👍🏻

**Comment by BreakBB** [comment]
Also thank you very much for your donation <3 @PapaBear138

**Comment by PapaBear138** [comment]
Absolutely!  Take care and have a wonderful day!  😊
