### ISSUE TITLE
Update Ace3 Libs

### ISSUE THREAD

**Issue by DustinChecketts** [BreakBB/ExtendedCharacterStats#241]
In WoW: Classic 1.14.4 PTR I receive an error from within the /Libs/Ace3/ folder upon fresh load. Updating all your Ace3 dependencies/libraries fixes this. Just thought you wanted to know.

**Comment by BreakBB** [comment]
Hey @DustinChecketts thanks a lot for letting me know about this! No clue how I forgot about this for so long 🤦🏻‍♂️

**Comment by BreakBB** [comment]
Fixed in e14a3cb00980f4c894ffbea716c6dad3bd9409db
