### ISSUE TITLE
Classic ERA ECS v3.1.2 (version from 1 day ago) isn't displaying hit correctly

### ISSUE THREAD

**Issue by mimixy** [BreakBB/ExtendedCharacterStats#242]
the melee hit rating section on Classic ERA is not showing the correct numbers.

in the screenshot i am waring 7% hit. but the miss chance against a level 60 and 63 mob isn't showing the correct values.

![image](https://github.com/BreakBB/ExtendedCharacterStats/assets/143043909/48df0b92-0efe-4aaf-ac3d-eb74d0722c88)

**Comment by BreakBB** [comment]
Hey @mimixy are you dual-wielding?

**Comment by mimixy** [comment]
> Hey @mimixy are you dual-wielding?

I am yes.

**Comment by mimixy** [comment]
I put a shield on, and it shows 0% miss now. I understand it's showing off hand miss chance? Is there a way for the MH and OH hit stats to be displayed seperately? both are important stats.

**Comment by BreakBB** [comment]
When dual-wielding you get an extra 19% miss chance for BOTH main and off-hand white hits. Therefore ECS shows you these miss chances.

The bonus you need for attacks to hit stays at 7% (or 8%?) regardless though.

So I am not sure if there would be a benefit splitting these values for MH and OH.

**Comment by mimixy** [comment]
I think I am confusing the warrior special attack hit chance and MH/OH. when you have 9% hit on gear, you special attacks don't miss. Can that distinction be made in the stats?

**Comment by BreakBB** [comment]
I guess it can, yes. I agree it's not really self explaining that the miss chance is for white hits and not special attacks, especially when dual-wielding.
