### ISSUE TITLE
Classic ERA Spell hit calculation from Talent Tree - Mage example attached

### ISSUE THREAD

**Issue by mimixy** [BreakBB/ExtendedCharacterStats#246]
Hi there me again. The spell hit calculation of ECS may have changed with the latest ERA patch. I think talent ID's all changed. I think your addon was checking for spell hit talents. For example the mage Elemental Precision 3/3 talent in the frost tree gives 6% hit. The hit vs 63 mobs should show 1% miss change, not 7. It seems to be missing that 6% from the talent as mage. Root cause is prob a change in the talent ID. 
![image](https://github.com/BreakBB/ExtendedCharacterStats/assets/143043909/24481e37-5e07-4e41-96b8-921518c8e27f)

**Comment by BreakBB** [comment]
Ouh, that could indeed be! Thanks for reporting this again, I'll take a look!
