### ISSUE TITLE
Classic HC Fire crit talents not showing the right crit%

### ISSUE THREAD

**Issue by Lagelito** [BreakBB/ExtendedCharacterStats#247]
Talent Critical Mass 3/3 only showing 4% crit instead of the intended 6%
I noticed that when I added the first point of the Talent it didn't increase the crit % in the addon. But 2 and 3rd point did.

## Screenshots
![image](https://github.com/BreakBB/ExtendedCharacterStats/assets/42940895/a490cccc-90c2-4b3f-9efb-a0fad6128d6f)
![image](https://github.com/BreakBB/ExtendedCharacterStats/assets/42940895/8ef9f2e6-2f50-48dd-9ea7-88d423d87a17)

v3.1.2 of the addon.

**Comment by BreakBB** [comment]
Hey @Lagelito someone else also hinted that the talents doesn't seem correct. I still need to look into that to verify.

Can you do me a favor, run the following command and report the output?

`/dump GetTalentInfo(2, 13)`

**Comment by Lagelito** [comment]
![image](https://github.com/BreakBB/ExtendedCharacterStats/assets/42940895/14eabc2f-765c-49e9-a0a3-8411aeef3c99)

[1]="Fire power",
[2]=135817,
[3]=6,
[4]=3,
[5]=5,
[6]=5,
[8]=1,
[10]=1,
[11]=35

**Comment by Lagelito** [comment]
![image](https://github.com/BreakBB/ExtendedCharacterStats/assets/42940895/bff9b998-8171-4922-b27f-c8a3389f338b)

After I logged into today its now showing as 14.74% crit instead of the 10.74%

**Comment by BreakBB** [comment]
> ![image](https://user-images.githubusercontent.com/42940895/265699893-14eabc2f-765c-49e9-a0a3-8411aeef3c99.png)
> 
> [1]="Fire power", [2]=135817, [3]=6, [4]=3, [5]=5, [6]=5, [8]=1, [10]=1, [11]=35

Oh boy, thank you very much. Looks like I really need to go through all talents again to verify they are used correctly 🙈

**Comment by Lagelito** [comment]
I noticed another thing with Combustion.  Doesn't count in either. :D Sorry for making extra work :')
![image](https://github.com/BreakBB/ExtendedCharacterStats/assets/42940895/c78315b3-08a0-46f4-a0da-fb52e22a176f)
