### ISSUE TITLE
Aspect of the Cheetah is sometimes not recognized correctly

### ISSUE THREAD

**Issue by BreakBB** [BreakBB/ExtendedCharacterStats#249]
## Bug description

Sometimes Aspect of the Cheetah is recognized correctly and the movement speed is at 136%.
But also this is not recognized correctly and even with Aspect of the Cheetah the movement speed stays at 100%.
Then again sometimes without Aspect of the Cheetah the movement speed shows 136%.

This could be related to #193 or could be a general API issue, as this was reported for Classic Hardcore.

## Screenshots

-

## Version

v3.1.3

**Comment by BreakBB** [comment]
Some more input on this:

One talent point just spent into AotC:

ECS shows 40% instead of 133%
![image](https://github.com/BreakBB/ExtendedCharacterStats/assets/33514570/27aac58e-bcf4-4c8b-b38d-3383b6adf364)

After switching to another Aspect it says 133%, then back to AotC says 100%.
So ECS is one aura-switch off as it seems.

Also API values:

With AotC (ECS shows 100%) ❌ 
![image](https://github.com/BreakBB/ExtendedCharacterStats/assets/33514570/8e37789d-57e6-40af-a1dd-d32edcc3c2ef)

Without any Aspect (ECS shows 133%) ❌ 
![image](https://github.com/BreakBB/ExtendedCharacterStats/assets/33514570/74832a9e-b7cd-4d4c-8553-08da685770b7)

Then switching to Aspect of the Monkey (ECS shows 100%) ✅ 
![image](https://github.com/BreakBB/ExtendedCharacterStats/assets/33514570/45df09e3-c3aa-40a3-a8da-95331e3df224)

**Comment by bkuepfer-revcomm** [comment]
I have been experiencing the same issue regarding movement speed. 
It is weird, it seems not to be able to keep track of the correct movement speeds. 
I would love to see this fixed! as it is the topmost stat and actually useful!

**Comment by BreakBB** [comment]
Hey @bkuepfer-revcomm yeah, this really is annoying and I have yet to find a fix/workaround for this. Time is limited though, but I hope to get some time soon for this 🙈
