### ISSUE TITLE
I translated that into french :D

### ISSUE THREAD

**Issue by Chironeyes** [BreakBB/ExtendedCharacterStats#25]
## Finally in french  !

First, thanks for this fresh addon !

I searched for a french version but i can't find it, probably it doesn't exist ? =p

So I made some modifications to translate it into french.
[This is the link](https://drive.google.com/file/d/1DRAE8CAHjKv9_IADZkmDzKGrZW-R1Ob-/view?usp=sharing) to my french version ! (from google drive) :)

**Game Version : 1.13.4.33920
ECS Version : 2.2.1**

Cheers !

PS: I added my nickname to the readme and the .toc file ^^''

**Comment by BreakBB** [comment]
@GeekToBe1 Thank you very much for this. I already added the first steps for this addon to be translated into multiple languages and it will be easy to add your French translations :+1:

**Comment by BreakBB** [comment]
Hey @GeekToBe1 I finally finished the logic to change the language and added a first translation (German).

Could you go through the strings again and match it with the translations you already added to your google document? I have no clue about French and don't really want to "guess" when translating/matching the texts.

**Comment by GeekToBe1** [comment]
I went to see and you did realy good work ! Congratulations :) 
However, the settings button seems broken and **/esc config** command doesn't work =/ (Command don't be sent and stay in chat textbox...)

(Wow Classic) Can you fix that please ? Cause I want to change language x)

**Important questions :**
After create **fr.lua** I uncomment Line 129 in **Config.lua** "_-- ["frFR"] = "Français_"," and at line 18 in **i18n.lua** I change first else into elseif and add one "else i18n:UseFrench()" and that's all ?

**Comment by GeekToBe1** [comment]
Work done boss !
[fr.lua](https://drive.google.com/file/d/1io2ycxtBjTjGXV8ilCm0TU2Fe14eChfR/view?usp=sharing)

Im waiting to your future replies :)

**Comment by BreakBB** [comment]
@GeekToBe1 Wow mate. That was really quick! I hope to include this very soon in an updated and fixed version of ECS
