### ISSUE TITLE
Spell Crit Not Equal to Frost Crit (Mage)

### ISSUE THREAD

**Issue by hankinsohl** [BreakBB/ExtendedCharacterStats#26]
On my mage, the ECS pane, under "Spell" shows "15.97%" crit.

But under "Spell Bonus", Frost Crit (and indeed crit for all other schools of magic) is listed as "12.97%." 

This seems to be a bug.
===
Edit: It appears that GetSpellCritChance does not account for talents.  Arcane Instability (+3 crit chance) is not included.

**Comment by BreakBB** [comment]
@hankinsohl Sorry for not responding to this earlier. I've been pretty bussy IRL, but hope to find the time to update ECS very soon.
