### ISSUE TITLE
Mp5 from Prophetic Aura ZG Enchant not included in calculation

### ISSUE THREAD

**Issue by ashtaar007** [BreakBB/ExtendedCharacterStats#28]
Extended character stats version: 3.4.1

![halo  of transcendence](https://user-images.githubusercontent.com/6677165/79661200-3ac5e200-8182-11ea-96e0-7c89f64cf4b4.png)
![with helm](https://user-images.githubusercontent.com/6677165/79661224-3c8fa580-8182-11ea-9b6d-a550183d299d.png)
![without helm](https://user-images.githubusercontent.com/6677165/79661310-42858680-8182-11ea-9065-684439d398d9.png)

**Comment by Windermericon** [comment]
Hello, this is marked as closed but the regen from the priest ZG enchant doesn't seem to be being counted, please see screenshots and thanks for your mod!
![priest t2 legs with fr enchant](https://user-images.githubusercontent.com/65980709/82951154-94e66e00-9f9e-11ea-9ad9-4e5cc40f0d77.png)
![priest t2 legs with zg enchant](https://user-images.githubusercontent.com/65980709/82951155-957f0480-9f9e-11ea-8ef7-71a89a4b5141.png)
![regen with zg t2 leggings](https://user-images.githubusercontent.com/65980709/82951156-96179b00-9f9e-11ea-88e5-590aebfd0703.png)
![regen with fr t2 leggings](https://user-images.githubusercontent.com/65980709/82951157-96b03180-9f9e-11ea-9112-d3a363ce6bbc.png)
