### ISSUE TITLE
Display block value along with block chance

### ISSUE THREAD

**Issue by danweiss90** [BreakBB/ExtendedCharacterStats#29]
## Description
Currently only block chance is displayed (The tooltip states block value which should be changed to block chance). Displaying block value would also be helpful.

This can be found with GetShieldBlock() .

**Comment by BreakBB** [comment]
Hey @danweiss90 Sorry for not responding to this earlier. Yes, block value would a good addition to ECS and I hope to have the time to add it very soon.
