### ISSUE TITLE
Settings no longer working; /ecs config not working

### ISSUE THREAD

**Issue by adrianveen** [BreakBB/ExtendedCharacterStats#314]
## Bug description
the /ecs config command is not working. the settings button is not working either. Clicking on settings results in nothing. when you type /ecs config it won't let you hit enter to send the command. 

## Screenshots
![image](https://github.com/BreakBB/ExtendedCharacterStats/assets/25138362/3a7a3f70-5690-4806-af16-5f32355d1548)

## Version
Classic Era/SoD - v3.3.0

**Comment by BreakBB** [comment]
This is related to #309 and will be fixed in the next release, which will be available in a few minutes.
