### ISSUE TITLE
Wrong MP5 in SoD

### ISSUE THREAD

**Issue by lgpasquale** [BreakBB/ExtendedCharacterStats#318]
## Bug description
Some MP5 values seem to be wrong in SoD.
I think there are 3 issues.
||How it's currently computed|How it should be|
|-|-|-|
|MP5 (Spirit)|Formula at MP5.lua#L93|GetManaRegen()|
|MP5 (Casting)|GetManaRegen()*mod + mp5Items + auraValues|Should be ok, but displayed value is wrong (see screenshot below)|
|MP5 (Not Casting)|GetManaRegen()|GetManaRegen() + mp5Items + auraValues|

**MP5 (Spirit)**
For the "MP5 (Spirit)", I think you can simply use GetManaRegen(). Alternatively, the correct formula I think should be:
- Priests and mages: 13 + (spirit / 4) mana per tick
- Druids, shamans, paladins, hunters: 15 + (spirit / 5) mana per tick
- Warlocks: 8 + (spirit / 4) mana per tick

**MP5 (Casting)**
The "MP5 (Casting)" value should be correct, judging by a quick look at the code; however the value displayed is wrong. There must be a bug somewhere but I can't find it.
In this screenshot I have 3 points in the Reflection talent, which grants 15% mana regen while casting.
The "MP5 (Casting)" value however is much lower than what it should be.
![Screenshot from 2024-04-25 19-43-31](https://github.com/BreakBB/ExtendedCharacterStats/assets/6189354/5fc8f456-0409-45dd-aa74-969bdd0b741d)

**MP5 (Not casting)**
This value does not include the MP5 from items and auras. If this is intended it's a bit misleading.

## Version
ExtendedCaracterStats v3.3.1

**Comment by BreakBB** [comment]
Hey @lgpasquale sorry for not looking into this earlier.

It indeed looks like the MP5 code didn't age well. There are indeed many issues and the overview you provided helps a lot when looking into it.

I am quite sure I'll be able to fix this rather soon and ship another release.

**Comment by BreakBB** [comment]
Alright `GetManaRegen` now includes the mana reg changes from talents (such as "Reflection"). I am quite sure it didn't in the past, which is why I added all kind of extra checks.
