### ISSUE TITLE
stats not showing up

### ISSUE THREAD

**Issue by Quabityyyy** [BreakBB/ExtendedCharacterStats#319]
## Bug description
stats do not show up under the two window selections below your character when you press "c". I reloaded, uninstalled and reinstalled the addon, and nothing is working

## Version
3.4.3

**Comment by BreakBB** [comment]
Hey @Quabityyyy

can you provide a screenshot and/or some more information? What game version are you playing? Era, SoD or WotLK?

> stats do not show up under the two window selections
I have no clue what you mean by that.

The ECS window will be on the right of the character panel as you see in this screenshot:

![image](https://github.com/BreakBB/ExtendedCharacterStats/assets/33514570/882aac8a-dd71-4a5c-b873-ffe4e7096f35)
