### ISSUE TITLE
Affliction warlock's Suppression talent incorrectly adds bonus spell hit in Classic Era

### ISSUE THREAD

**Issue by RA80533** [BreakBB/ExtendedCharacterStats#321]
## Bug description
In Classic Era, affliction warlock's Suppression talent is a 5-point talent that adds bonus spell hit for affliction spells. In Wrath, the talent is a 3-point talent that adds bonus spell hit for all spells.

Extended Character Stats treats the talent as its Wrath-era version even if the game client is running Classic Era.

## Version
ECS v3.3.2

**Comment by BreakBB** [comment]
Closing in favor of #328
