### ISSUE TITLE
Total Spell hit on Classic Era calculated incorrectly

### ISSUE THREAD

**Issue by retrobloodfang** [BreakBB/ExtendedCharacterStats#326]
## Bug description
On my mage ECS displays the following:
Bonus: 7.14%
Miss: 1%
Miss (Lvl + 3): 9.86%

However, I know for a fact I’m at a way higher hit. i have the following hit contributions:
Talents into ‘Elemental Precisioin’: 3/3 (6% hit)
Total hit from gear: 8%
Total hit aquired should be: 14%

It used to work fine but it broke since the WoW SoD patch. So I’m sure it’s the Addon.

## Screenshots
![image](https://github.com/user-attachments/assets/ffa56f57-a8df-4cd5-880d-1246a0e5b2ef)

## Version
Classic Era
ECS v3.3.4

**Comment by BreakBB** [comment]
Thanks for reporting this. It reminded me, that Blizzard changed the talent order and now I have to do all checks over again 🙈

**Comment by retrobloodfang** [comment]
I also commented on a post saying spell hit in SoD was incorrect and I noticed the same in Era. You may want to look at the SoD topic too.
https://github.com/BreakBB/ExtendedCharacterStats/issues/325

**Comment by BreakBB** [comment]
hmmm... It is looking fine for me on SoD with my mage 🤔 

`/dump GetTalentInfo(3, 17)` still is Elemental Precision

**Comment by retrobloodfang** [comment]
Cool, maybe not. Don’t play SoD, just Era and in Era there’s definitely an issue. Thanks for looking into it!

**Comment by BreakBB** [comment]
Found the issue. It affects both Era and SoD. Fix will be released shortly.

**Comment by retrobloodfang** [comment]
Thanks in advance for the hot fix!
