### ISSUE TITLE
Spell hit for Shaman shows 6% from talent Nature's Guidance when the talent tree correctly shows 3%

### ISSUE THREAD

**Issue by carrera987** [BreakBB/ExtendedCharacterStats#329]

**Comment by BreakBB** [comment]
Hey @carrera987 thanks for reporting this. I assume this is for Era/SoD?

**Comment by BreakBB** [comment]
Could you run the following in the chat and report the output?

`/dump GetTalentInfo(3,3)`

I can't find an issue on this.

**Comment by carrera987** [comment]
Thank you for checking!

Yes this is for SoD

I did run the command. The game lagged for a second but nothing changed. It
still shows 6% just from those talents when it should be 3%

I tried repotting as well after the script command

**Comment by BreakBB** [comment]
The command should print something to the chat. I need to see that. It won't cause any lag.

**Comment by carrera987** [comment]
Ok I ran it and this is what my chat said

[1]=“Nature’s Guidance”,
[2]=135860,
[3]=3,
[4]=1,
[5]=3,
[6]=3,
[7]=1,
[8]=3,
[9]=1,
[12]=583

**Comment by BreakBB** [comment]
This looks absolutely correct.

Can you share a screenshot of the issue?

**Comment by BreakBB** [comment]
I think you actually need to visit the issue https://github.com/BreakBB/ExtendedCharacterStats/issues/329 and can not send images via mail response.

**Comment by carrera987** [comment]
![1](https://github.com/user-attachments/assets/e5ab7c53-95d6-4d27-9f8c-568e756dccab)
I turned off all other add ons to make sure that wasn’t the issue. I even respeced to clear my talents. This is showing 0 hit gear equipped and no talents

**Comment by carrera987** [comment]
![2](https://github.com/user-attachments/assets/2853eb54-fe47-4922-8295-6ece86f67c7c)
This is still showing no hit gear equipped and when I put 3 talent points into Natures Guardian. It should give me 3% hit and this is showing 6


I don’t know if this helps. When I put in the talents it showed 0% originally. Then when I equipped a helm with 1 hit I briefly saw it go to 3% then 4% and then it changed in a flash to 7%. When I took helm off it went back down to 6% and is staying there. It’s somehow adding double the points and I saw it change briefly which makes it seem like it’s calculating it from somewhere and adding it twice in a longer script

**Comment by BreakBB** [comment]
Thanks a lot for these screenshots and the detailed response @carrera987 !

> I don’t know if this helps. When I put in the talents it showed 0% originally.

Hmmm... This should not happen. Looks like I need to make sure again this is working correctly 🙈 

> Then when I equipped a helm with 1 hit I briefly saw it go to 3% then 4% and then it changed in a flash to 7%. When I took helm off it went back down to 6% and is staying there. It’s somehow adding double the points and I saw it change briefly which makes it seem like it’s calculating it from somewhere and adding it twice in a longer script

This sounds related to #313

Tbh ECS didn't get much love in the last month, as Questie is talking most of my free time...

If you want to help out more then it would be great if you could run the following commands in the chat and also report the outcome. These are sanity checks, which will help me to pin down where to look for the actual issue:

1. `/dump CR_HIT_SPELL`
2. (if the first returns something else than "empty value" then run: `/dump GetCombatRatingBonus(CR_HIT_SPELL)`
3. `/dump GetSpellHitModifier()`
4. `/dump ECSLoader:ImportModule("Data"):SpellHitBonus()`

**Comment by carrera987** [comment]
Ok thank you for checking again. I did not know that you do Questie as well - that is a very needed addon! I can definitely help on my end.

1. running this shows

CR_HIT_SEPLL=nil,
empty result

2. running this shows

Dump: value=GetCombatRatingBonus(CR_HIT_SPELL)

3. running this shows

Dump: value=GetSpellHitModifier()
[1]=3

4. running this shows

Dump: value=ESCLoader:ImportModule("Data");SpellHitBonus()
[1]="6%"


This is with no gear on and just hit from the talents which again should be 3%. When I switch to resto spec with no hit talents ECS correctly displays 0%

**Comment by BreakBB** [comment]
Thanks @carrera987 we found the issue!

ECS calculates the talent bonus manually and add the result from `GetSpellHitModifier()`. In the past `GetSpellHitModifier` did not include hit from talents, which it does now 🤦🏻

**Comment by BreakBB** [comment]
I wonder if that is also an issue for all other classes with hit talents... 🙈

**Comment by BreakBB** [comment]
Hey @carrera987 a fixed version will be available in a few minutes. It would be great if you could install that one and report back if everything is calculated correctly now.

**Comment by carrera987** [comment]
Yes I just checked and it works perfectly - thank you for fixing this! Also before you updated I tried my hunter and the hit did work correctly, seems like it was only an issue for Shamans.
