### ISSUE TITLE
ECS causes major lagg in SoD raids

### ISSUE THREAD

**Issue by Azuriella** [BreakBB/ExtendedCharacterStats#330]
In raid, this addon causes screen stutters every 2-3 secs, it's especially bad in 40 man MC.

No screenshot, but I noticed the addon taking close to 300 mb of memory in raid, causing screen stutters. Disabling the addon solved the issue

Classic Era

**Comment by BreakBB** [comment]
Ohhh... I _think_ I know what is going on. I read about Blizzard firing up a huge amount of events since the latest patch, which addons need to process.

I'll add a check for it, ship a new version and it would be great if you could provide feedback on it.

**Comment by BreakBB** [comment]
Please grab v3.3.9 and see if that helps.

**Comment by Azuriella** [comment]
> Please grab v3.3.9 and see if that helps.

I'll test it on wed, thanks for your work :)

**Comment by BreakBB** [comment]
> > Please grab v3.3.9 and see if that helps.
> 
> I'll test it on wed, thanks for your work :)

Great, looking forward to your feedback 👍🏻

**Comment by BreakBB** [comment]
Hmmm... I'll take a another look at this @Azuriella

**Comment by BreakBB** [comment]
Another version is out @Azuriella also addressing this issue

**Comment by BreakBB** [comment]
Hey @Azuriella did you have the chance to test this again?

**Comment by BreakBB** [comment]
Went through raids in SoD myself and didn't experience any issues.

Feel free to open up a new issue if anything comes up again.
