### ISSUE TITLE
Ranged miss% vs lvl+3 displaying incorrect info

### ISSUE THREAD

**Issue by deej009** [BreakBB/ExtendedCharacterStats#331]
## Bug description
The first 1% of +hit from gear/talents is being ignored for ranged miss chance vs lvl+3 mobs.
It's also my understanding through [this blue post here](https://www.wowhead.com/classic/news/hit-cap-in-classic-wow-clarifications-292085) that, although the hitcap is 9%, the miss% should still be 8% too unless they changed that formula after classic in 2019-2020.

## Without blackstone ring equipped:
![image](https://github.com/user-attachments/assets/a55b9725-4d02-4ba2-acdd-50e52135d016)

## With blackstone ring equipped:
![image](https://github.com/user-attachments/assets/1d0ed18a-fd28-4a18-adaa-e4354752344c)

**Comment by BreakBB** [comment]
Hey @deej009 

Thanks for reporting this. Something seems off, true. I'll look into it.

**Comment by BreakBB** [comment]
Alright, so this is indeed working correctly as explained in #86 and confirmed from [the Hunter Discord](https://discord.com/invite/classic-hunter-lodge-253213664708919296).

Yes, the first Hit-% is effectively ignores. But only if you have less than 305 weapon skill.

Details in [this spreadsheet](https://docs.google.com/spreadsheets/d/1pumaTQgj-H5IOkvU0sMaa-HPJmj55O2eRSpfPr93nBM)

**Comment by deej009** [comment]
Right, that's why the hit cap is 9% instead of 8%, the issue is that your
addon shows that there's still a 1% chance to miss when 9% hit from
gear/talents is equipped.

It should display either 9% hit required  or 8% hit required and ignore the
first 1%, but right now it's doing both at the same time and wants me to
wear a full 10% hit in order to not miss on raid mobs.

**Comment by BreakBB** [comment]
Thanks for coming back to this @deej009 

I'll look into that. The goal is to get down to 0% with 9% hit equipped
