### ISSUE TITLE
ECS not attached to CharacterFrame

### ISSUE THREAD

**Issue by GiurlaniDev** [BreakBB/ExtendedCharacterStats#332]
## Bug description

My ECS panel doesn't attach to the CharacterFrame. Any ideas on how to fix it?
I'm currently running Rune Reminder which gets rid of the runes UI that's usually attached to.
 

## Screenshots
![Dow7Isv](https://github.com/user-attachments/assets/ca2005f6-6b8b-415f-8583-932e2a382c86)

## Version
**Classic - Season of Discovery**
**Interface:** 11505
**Title:** Extended Character Stats v3.3.13
**Version:** 3.3.13

**Comment by GiurlaniDev** [comment]
In **line 103** of the **Stats.lua** file, I changed the following:

```
if ECS.IsSoD then
    C_Timer.After(0.3, function ()
        if CharacterFrame then
            mainFrame:ClearAllPoints()
            mainFrame:SetPoint("LEFT", CharacterFrame, "RIGHT", -30, 20)
        end
    end)
end
```

However, this makes it lose the ElvUI skin on the frame, no idea why. Any clues?

**Comment by BreakBB** [comment]
Hey @GiurlaniDev 

Thanks for bringing this up. I never fiddled with ElvUI as I can't stand the theme. But it absolutely looks like it somehow breaks the positioning of the ECS frame.

I'll see what I can come up with to fix this!

**Comment by BreakBB** [comment]
Hey @GiurlaniDev The fix is released. I didn't test it with ElvUI, but Rune Reminder indeed resulted in the gap between ECS and the character frame.

Also thanks for telling me about Rune Reminder, I'll keep it :D
