### ISSUE TITLE
Zandalar's set bonus mp5 doesn't counted

### ISSUE THREAD

**Issue by vrubinets** [BreakBB/ExtendedCharacterStats#34]
## Bug description
Very nice addon, I have a lot of fun when using it.
But found an issue with calculating MP5. 
Zandalar's set bonus (4 mana per 5 sec) does not counted in the total value. 
See screenshots with and without bonus set.

## Screenshots
![WoWScrnShot_051820_235242](https://user-images.githubusercontent.com/52156928/82263221-b58d4300-9962-11ea-841d-c27b1aeeada0.jpg)
![WoWScrnShot_051820_235234](https://user-images.githubusercontent.com/52156928/82263224-b6be7000-9962-11ea-9cc4-e89c3b28c0bc.jpg)

## Version
v2.3.0

**Comment by BreakBB** [comment]
@vrubinets Thanks for reporting this. Addons like these really depend on the users reporting issues they are experiencing 🙏  I will try to get a 2p bonus on my Druid very soon to be able to test this while fixing it.
