### ISSUE TITLE
Addon not appear

### ISSUE THREAD

**Issue by Sudargo** [BreakBB/ExtendedCharacterStats#36]
After downloaded the addon, click enable in game, it still does not show in the character page.
Tried /ECS command too, but none happen after pressing enter

**Comment by GeekToBe1** [comment]
I have the same issue.
Strange -> After that I put 2.2.1 version then I launch the game and close it. Next I replace it by 2.4.2 and it works but settings button and "/ecs toggle" command dosen't work. I think there is something in WTF folder that help 2.4.2 works after replacing old 2.2.1.

**Comment by BreakBB** [comment]
@Sudargo @GeekToBe1 Sorry for the trouble. Looks like I missed something essential when changing the loading of settings.

**Comment by BreakBB** [comment]
@Sudargo You might want to update to v2.4.4 and try again.
