### ISSUE TITLE
Error occurs as soon as I login after installation

### ISSUE THREAD

**Issue by goodey** [BreakBB/ExtendedCharacterStats#37]
## Bug description
Date: 2020-05-24 13:58:01
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\ExtendedCharacterStats\ECS.lua line 46:
   attempt to index local 'ecs' (a nil value)
Debug:
   ExtendedCharacterStats\ECS.lua:46:
      ExtendedCharacterStats\ECS.lua:41
   ExtendedCharacterStats\ECS.lua:31:
      ExtendedCharacterStats\ECS.lua:28
Locals:
ecs = nil
defaultProfile = <table> {
 general = <table> {
 }
 profile = <table> {
 }
}
profileVersion = 3
(*temporary) = <table> {
 private = <table> {
 }
 GetDefaultProfile = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Profile.lua:143
 GetProfileVersion = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Profile.lua:8
}
(*temporary) = 3
(*temporary) = "attempt to index local 'ecs' (a nil value)"
Profile = <table> {
 private = <table> {
 }
 GetDefaultProfile = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Profile.lua:143
 GetProfileVersion = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Profile.lua:8
}
i18n = <table> {
 UseGerman = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\i18n\de.lua:6
 LoadLanguageData = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\i18n\i18n.lua:6
 UseEnglish = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\i18n\en.lua:6
 SetLanguage = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\i18n\i18n.lua:24
 private = <table> {
 }
 translate = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\i18n\i18n.lua:30
}

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AtlasLootClassic, vv1.5.1
  AtlasLootClassicData, vv1.5.1
  AtlasLootClassicDungeonsAndRaids, vv1.5.1
  ClassicCastbars, vv1.3.6
  ClassicCastbarsOptions, v
  ClickLinks, v1.0.8
  DBMCore, v1.13.45
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  ExtendedCharacterStats, v2.4.2
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v1.13.4.11304 <none>
  (ck=252)

## Version
v2.4.2 , also happened with v2.4.0

**Comment by GeekToBe1** [comment]
I can confirm that happen with 2.4.0 too

**Comment by BreakBB** [comment]
@goodey Thanks for the report. I must have missed something when changing that part of the addon. I will push out an update soon

**Comment by goodey** [comment]
No problem, tried to have a quick look myself but bit new to Lua.

**Comment by BreakBB** [comment]
@goodey No worries I already found the issue. But won't be able to release on update for the next 7-8 hours since I have to sleep :D Will be the first thing in the morning.
