### ISSUE TITLE
ECS not working anymore

### ISSUE THREAD

**Issue by djwilson2** [BreakBB/ExtendedCharacterStats#38]
## Bug description
Receive the following error :

> Date: 2020-05-24 11:14:20
ID: 3
Error occured in: Global
Count: 1
Message: ..\AddOns\ExtendedCharacterStats\ECS.lua line 129:
   attempt to call upvalue 'i18n' (a table value)
Debug:
   [C]: ?
   ExtendedCharacterStats\ECS.lua:129: ?()
   ..\FrameXML\ChatFrame.lua:4690:
      ..\FrameXML\ChatFrame.lua:4637
   [C]: ChatEdit_ParseText()
   ..\FrameXML\ChatFrame.lua:4351: ChatEdit_SendText()
   ..\FrameXML\ChatFrame.lua:4387: ChatEdit_OnEnterPressed()
   [string "*:OnEnterPressed"]:1:
      [string "*:OnEnterPressed"]:1
Locals:

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AdiBags, vDEV
  AtlasLootClassic, vv1.5.1
  AtlasLootClassicData, vv1.5.1
  AtlasLootClassicDungeonsAndRaids, vv1.5.1
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucScanData, v8.2.6365 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  ClassicCastbars, vv1.3.6
  ClassicCastbarsOptions, v
  ClassicHealPrediction, vv1.6.6
  D4KiRHealerProtection, v5.7 Release
  DBMCore, v1.13.45
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Decursive, v2.7.7
  Details, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  Elephant, v1.13.3d
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  ExtendedCharacterStats, v2.2.1
  FishingBuddy, v0.7.3 Beta 5
  GatherMate2, v1.45.5
  GSE, v2.5.5
  GSEGUI, v2.5.5
  GSELDB, v2.5.5
  Healium, v
  honorspy, v1.7.3
  Informant, v8.2.6374 (SwimmingSeadragon)
  LeatrixMaps, v1.13.63
  LeatrixPlus, v1.13.63
  MacroTalkClassic, v1.1.1
  NovaWorldBuffs, v1.53
  NPCRPGossipClassic, v1.0.3
  PowerAuras, v4.31.0
  QoLClassicHeals, v17
  QoLCore, v14
  Questie, v5.10.3
  Recount, vv1.13.4b
  ShowMeMyHeal, v0.6.1
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Spy, v1.0.27
  Stubby, v8.2.6376 (SwimmingSeadragon)
  ThreatClassic2, v2.19
  totalRP3, v1.6.11
  totalRP3Data, v
  TwitchEmotes, vv2
  VendorPrice, v1.3.5
  Wardrobe, v2.0.0
  WeakAuras, v2.17.5
  BlizRuntimeLib_enUS v1.13.4.11304 <none>
  (ck=6ed)

> 

## Version

5/24/20 | v2.4.2
-- | --

**Comment by BreakBB** [comment]
Did you restarted WoW after updating ECS?

**Comment by djwilson2** [comment]
Yes, I exited the WoW program, but not the battle.net program.

**Comment by BreakBB** [comment]
@djwilson2 I can't reproduce this. Could you send me the following file after the error appears:

`_classic_/WTF/Account/<YourAccount>/<YourServer>/<YourCharacter>/SavedVariables/ExtendedCharacterStats.lua`

You can save it either as .zip file or change it to be a .txt file and then simply drag and drop it here on GitHub.

**Comment by helvexis** [comment]
I am getting 
 Invalid Custom Control Type - LQDropdown message when i login since updating.

**Comment by BreakBB** [comment]
@helvexis Could you disable all addons except ECS and try again?

**Comment by helvexis** [comment]
yeah. that fixes it.

**Comment by BreakBB** [comment]
@djwilson2 @helvexis You should update to v2.4.4 and try again.

**Comment by GeekToBe1** [comment]
@BreakBB 2.4.4 fix all ! =) Thanks !!!

**Comment by BreakBB** [comment]
@GeekToBe1 Thanks for your fast responses and testing. Really appreciating it :+1:

If those ugly issues are fixed I can add your French translations in the next days and focus on other features :grin:

**Comment by djwilson2** [comment]
[ExtendedCharacterStats.lua.txt](https://github.com/BreakBB/ExtendedCharacterStats/files/4677982/ExtendedCharacterStats.lua.txt)

**Comment by djwilson2** [comment]
Loading version 2.4.4 fixed the problem.
Thank you.
