### ISSUE TITLE
Profiles to have different settings for each char

### ISSUE THREAD

**Issue by Nzash** [BreakBB/ExtendedCharacterStats#39]
Not sure if I'm missing something, but it seems like there is no such function right now and when I want to see all my spell stuff on the warlock I end up having to see them on my Warrior too and vice versa with other stats the Warlock might not care about.

If there truly isn't a way to have different profiles for ECS yet, can we get it? Thanks!

**Comment by BreakBB** [comment]
Hmmm... I never checked it, but by default the settings should be stored per character and not per account. But I will look into it and see to change it.
It really would be a good improvement :+1:

**Comment by BreakBB** [comment]
From what I've tested so far is that the stats are saved by character as it should be. Could you test again @Nzash to see if the values you disable are really shown again on other characters?

**Comment by Nzash** [comment]
Well, I apologize. It seems to work now. I swear I wasn't drunk yesterday and I don't know why it works today, but it does and clearly it was already intended to work this way, so... 

Sorry for wasting your time, all good :)
