### ISSUE TITLE
 Still some errors - settings doesn't work

### ISSUE THREAD

**Issue by GeekToBe1** [BreakBB/ExtendedCharacterStats#40]
## Bug description
There is 6 lua messages errors after launch.
Settings doesn't work and give two differents errors.

Note : Before upgrade to 2.4.3 version I delete **cache** and **WTF** folders
### 1/6

**Message**: ...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:12: Cannot find a library instance of "CallbackHandler-1.0".
**Time**: Mon May 25 10:11:29 2020
**Count**: 1
**Stack**: ...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:12: Cannot find a library instance of "CallbackHandler-1.0".
[C]: in function error'
...dOns\ExtendedCharacterStats\Libs\LibStub\LibStub.lua:23: in function LibStub'
...-3.0\AceConfigRegistry-3.0\AceConfigRegistry-3.0.lua:12: in main chunk

**Locals**: (*temporary) = "Cannot find a library instance of "CallbackHandler-1.0"."

### 2/6
**Message**: ...eConfigECS-3.0\AceConfigCmd-3.0\AceConfigCmd-3.0.lua:17: Cannot find a library instance of "AceConfigRegistryECS-3.0".
**Time**: Mon May 25 10:11:29 2020
**Count**: 1
**Stack**: ...eConfigECS-3.0\AceConfigCmd-3.0\AceConfigCmd-3.0.lua:17: Cannot find a library instance of "AceConfigRegistryECS-3.0".
[C]: in function error'
...dOns\ExtendedCharacterStats\Libs\LibStub\LibStub.lua:23: in function LibStub'
...eConfigECS-3.0\AceConfigCmd-3.0\AceConfigCmd-3.0.lua:17: in main chunk

**Locals**: (*temporary) = "Cannot find a library instance of "AceConfigRegistryECS-3.0"."

### 3/6
**Message**: ...gECS-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:8: Cannot find a library instance of "AceConfigRegistryECS-3.0".
**Time**: Mon May 25 10:11:29 2020
**Count**: 1
**Stack**: ...gECS-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:8: Cannot find a library instance of "AceConfigRegistryECS-3.0".
[C]: in function error'
...dOns\ExtendedCharacterStats\Libs\LibStub\LibStub.lua:23: in function LibStub'
...gECS-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:8: in main chunk

**Locals**: (*temporary) = "Cannot find a library instance of "AceConfigRegistryECS-3.0"."

### 4/6
**Message**: ...aracterStats\Libs\AceConfigECS-3.0\AceConfig-3.0.lua:15: Cannot find a library instance of "AceConfigRegistryECS-3.0".
**Time**: Mon May 25 10:11:29 2020
**Count**: 1
**Stack**: ...aracterStats\Libs\AceConfigECS-3.0\AceConfig-3.0.lua:15: Cannot find a library instance of "AceConfigRegistryECS-3.0".
[C]: in function error'
...dOns\ExtendedCharacterStats\Libs\LibStub\LibStub.lua:23: in function LibStub'
...aracterStats\Libs\AceConfigECS-3.0\AceConfig-3.0.lua:15: in main chunk

**Locals**: (*temporary) = "Cannot find a library instance of "AceConfigRegistryECS-3.0"."

### 5/6
**Message**: (null)
**Time**: Mon May 25 10:11:30 2020
**Count**: 23

### 6/6
**Message**: ...Ons\ExtendedCharacterStats\Modules\Config\Config.lua:27: Cannot find a library instance of "AceConfigECS-3.0".
**Time**: Mon May 25 10:11:31 2020
**Count**: 1
**Stack**: ...Ons\ExtendedCharacterStats\Modules\Config\Config.lua:27: Cannot find a library instance of "AceConfigECS-3.0".
[C]: in function error'
...dOns\ExtendedCharacterStats\Libs\LibStub\LibStub.lua:23: in function LibStub'
...Ons\ExtendedCharacterStats\Modules\Config\Config.lua:27: in function CreateWindow'
...face\AddOns\ExtendedCharacterStats\Modules\Stats.lua:84: in function CreateWindow'
Interface\AddOns\ExtendedCharacterStats\ECS.lua:73: in function <Interface\AddOns\ExtendedCharacterStats\ECS.lua:71>
Interface\AddOns\ExtendedCharacterStats\ECS.lua:35: in function <Interface\AddOns\ExtendedCharacterStats\ECS.lua:28>

**Locals**: (*temporary) = "Cannot find a library instance of "AceConfigECS-3.0"."

### 1/1
**Message**: ...face\AddOns\ExtendedCharacterStats\Modules\Stats.lua:53: attempt to index global 'ECSConfigFrame' (a nil value)
**Time**: Mon May 25 10:11:40 2020
**Count**: 1
**Stack**: ...face\AddOns\ExtendedCharacterStats\Modules\Stats.lua:53: attempt to index global 'ECSConfigFrame' (a nil value)
...face\AddOns\ExtendedCharacterStats\Modules\Stats.lua:53: in function <...face\AddOns\ExtendedCharacterStats\Modules\Stats.lua:52>

**Locals**: (*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'ECSConfigFrame' (a nil value)"

### 1/1
**Message**: ...Ons\ExtendedCharacterStats\Modules\Config\Config.lua:183: attempt to index global 'ECSConfigFrame' (a nil value)
**Time**: Mon May 25 10:17:22 2020
**Count**: 1
**Stack**: ...Ons\ExtendedCharacterStats\Modules\Config\Config.lua:183: attempt to index global 'ECSConfigFrame' (a nil value)
...Ons\ExtendedCharacterStats\Modules\Config\Config.lua:183: in function ToggleWindow'
Interface\AddOns\ExtendedCharacterStats\ECS.lua:126: in function `?'
Interface\FrameXML\ChatFrame.lua:4690: in function ChatEdit_ParseText'
Interface\FrameXML\ChatFrame.lua:4351: in function ChatEdit_SendText'
Interface\FrameXML\ChatFrame.lua:4387: in function ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>

**Locals**: self = <table> {
 private = <table> {
 }
 CreateWindow = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Config\Config.lua:25
 ToggleWindow = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Config\Config.lua:182
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'ECSConfigFrame' (a nil value)"

**Comment by BreakBB** [comment]
I didn't change anything about the loading of the libs so I wonder why those errors pop up now... I will try with a clean install soon and also without any other Addon loaded.

I am sorry for the trouble, I will try to improve my testing before releasing updates in the future.

**Comment by BreakBB** [comment]
Also @GeekToBe1 do those errors pop up every time log in? And did you try to disable all addons except ECS?

**Comment by GeekToBe1** [comment]
@BreakBB Yes everytime. But ECS window appear to and /ecs toggle and ecs button work. 
I haven't other addons installed actually

**Comment by BreakBB** [comment]
Nice, I can reproduce it without any other addon which will help a lot to fix it!

**Comment by GeekToBe1** [comment]
Great ! I'm realy excited about this future fix :)

**Comment by BreakBB** [comment]
@GeekToBe1 I have no idea how ECS did ever work with such issues... The loading of some required libraries did never fully work and some were even missing. So ECS heavily relied on other addons which were loaded before and included such libraries to even start.

The commit above fixes the loading and makes ECS not an independend addon 😄
