### ISSUE TITLE
MP5 from Wand not Registering

### ISSUE THREAD

**Issue by vexanix** [BreakBB/ExtendedCharacterStats#42]
MP5 from my wand is no longer being added to the MP5 (Items) or MP5 (Casting) sections. Currently using Essence Gatherer with 5 MP5. I don't have any other MP5 wands, or other characters with an MP5 Item for that slot to check. It did add it previously, I believe it stopped in the newest release.

![image](https://user-images.githubusercontent.com/65918348/82836026-bc044900-9e93-11ea-9f0c-ff75a6834803.png)

![image](https://user-images.githubusercontent.com/65918348/82836094-e35b1600-9e93-11ea-90a8-342cbbd9d81d.png)

**Comment by BreakBB** [comment]
@vexanix Ahhh, I know how that happened and it will be an easy fix. Sorry for the trouble

**Comment by vexanix** [comment]
@BreakBB No trouble at all. Thanks for making and supporting this addon!

**Comment by Molbork** [comment]
Still seeing this in v2.4.4, but that looks like it could be around the time of these comments...!

**Comment by BreakBB** [comment]
@Molbork Yeah, my time is quite limited in the last weeks, sorry. Once Questie v6.0.0 I can focus on ECS again 👍
