### ISSUE TITLE
Regen from the priest ZG enchant Prophetic Auranot being counted

### ISSUE THREAD

**Issue by Windermericon** [BreakBB/ExtendedCharacterStats#44]
Hello, this was marked as closed but the regen from the priest ZG enchant doesn't seem to be being counted and I'm not sure if my post in the closed thread will cause an alert, so please see screenshots and thanks for your mod!
![ecs regen with FR enchant](https://user-images.githubusercontent.com/65980709/83004106-24276c00-a007-11ea-8517-2b9490fcab47.png)
![ecs regen with ZG enchant](https://user-images.githubusercontent.com/65980709/83004109-24c00280-a007-11ea-9047-3b8e2fcf44a0.png)

_Originally posted by @Windermericon in https://github.com/BreakBB/ExtendedCharacterStats/issues/28#issuecomment-634284031_

**Comment by GeekToBe1** [comment]
I think you'r not in the good GitHub... Search the GitHub of your addon please...

**Comment by GeekToBe1** [comment]
I think you'r looking for https://www.curseforge.com/wow/addons/characterstatsclassic 
**Github** : https://github.com/getov/CharacterStatsClassic

**Comment by Windermericon** [comment]
Ugh, sorry, I posted the wrong screenshots - it's not working in either mod. Have updated with the correct screenshots

**Comment by BreakBB** [comment]
Merging this with #43
