### ISSUE TITLE
Stats window is anchored to PaperDollFrame

### ISSUE THREAD

**Issue by silverhawke249** [BreakBB/ExtendedCharacterStats#46]
## Bug description
after a certain version (unsure which, since i haven't updated in a while), the anchor for the stats window seems to have changed to PaperDollFrame, misplacing it if PaperDollFrame is moved in any way.

## Screenshots
![image](https://user-images.githubusercontent.com/50395934/83094179-ada47000-a0d3-11ea-93a8-0029ea0dbcb1.png)

as comparison, it looks fine on v2.3.0 -- going by the version label on curseforge
![image](https://user-images.githubusercontent.com/50395934/83094423-3f13e200-a0d4-11ea-9793-c79d9a0544fd.png)

## Version
version 2.4.4

**Comment by BreakBB** [comment]
@silverhawke249 Could you tell me which addon it is you're using there? That would help me to test your issue.

**Comment by silverhawke249** [comment]
it's my own -- not sure if others use it too since i don't 
publish this one on curseforge. you can find the repo here: https://github.com/silverhawke249/CharacterPageRearrange

**Comment by BreakBB** [comment]
@silverhawke249 Alright, thanks! Why are you not publishing it to Curseforge? Looks like some users will definately be interested in it 👍  You need to do some advertising (e.g. Reddit) about it though 😁 

I will look into it very soon to set the frame position based on the positing/size of the PaperDollFrame

**Comment by silverhawke249** [comment]
thank you, i appreciate it a lot!
i might publish it once i clean up the code/rewrite it since it's pretty much my first attempt at making an addon haha :P
