### ISSUE TITLE
Casting MP5 shows up wrong for shaman?

### ISSUE THREAD

**Issue by potatoeswatchyou** [BreakBB/ExtendedCharacterStats#49]
## Question
Why does the casting MP5 (200) on my shaman simply show up as MP5 from spirit (145) + MP5 from gear? (55)

Is this a problem with shaman? Shaman gets nothing from spirit unless using blue dragonscale.

**Comment by BreakBB** [comment]
@potatoeswatchyou Hmmm... This might be a bug. Can you share a screenshot of the values when you just completed a cast and after the 5 second rule? Also your gear might be interesting.

**Comment by potatoeswatchyou** [comment]
![MP5](https://user-images.githubusercontent.com/66976758/84973768-80058200-b0e7-11ea-9ccf-728df1a91e2f.jpg)

**Comment by potatoeswatchyou** [comment]
It is including my spirit mp5 in casting, it always says that. After i cast, while i cast, during a cast, before a cast

**Comment by potatoeswatchyou** [comment]
I feel like im doing something wrong because my mana spring totem doesnt make a difference either, but other shamans in my raid say it works for them

**Comment by BreakBB** [comment]
@potatoeswatchyou Thanks for coming back to this. There might be something wrong in the logic of ECS if the casting doesn't MP5 change 🤔 I will also check Manaspring totem once I have time again (which is hopefully soon ™️ )
