### ISSUE TITLE
Add localization

### ISSUE THREAD

**Issue by anon1231823** [BreakBB/ExtendedCharacterStats#51]
## Description
Add localization to addon

**Comment by BreakBB** [comment]
@anon1231823 I already have the data for German and English included and the next update will include French as well. For every other language I need someone to translate all the things 😃

**Comment by Chironeyes** [comment]
There is a temporary fix here posted by me in #52 issue

**Comment by Chironeyes** [comment]
There is a temporary fix in #52 post. 
Follow [this](https://github.com/BreakBB/ExtendedCharacterStats/issues/52#issuecomment-656065527) comment to set french translation 👍🏻

**Comment by BreakBB** [comment]
@anon1231823 Feel free to add the Russion translations as it has been done in #77
