### ISSUE TITLE
Missing translation in last version 2.4.6

### ISSUE THREAD

**Issue by edbob78** [BreakBB/ExtendedCharacterStats#52]
## Bug description

No translation (french) in last version

## Screenshots

![image](https://user-images.githubusercontent.com/68048411/87004037-70003000-c1c5-11ea-8030-a2358d55ee3e.png)
![image](https://user-images.githubusercontent.com/68048411/87004171-adfd5400-c1c5-11ea-8dfa-cba679e97f42.png)

## Version

2.4.6

**Comment by Chironeyes** [comment]
Hi, you can download my french translation from my googe drive [here](https://drive.google.com/file/d/1io2ycxtBjTjGXV8ilCm0TU2Fe14eChfR/view?usp=sharing)
And rename`ExtendedCharacterStats/Modules/i18n/`**en.lua** in `ExtendedCharacterStats/Modules/i18n/`**OLDen.lua**
then rename **fr.lua** that you'v downloaded in **en.lua** and put it in `ExtendedCharacterStats/Modules/i18n/`

Greetings ! 😀

**Comment by Chironeyes** [comment]
Hi dear edbob78 !
 
**Temporary solution til future realease implemented it**

1. Download my french translation from my Google drive [here](https://drive.google.com/file/d/1io2ycxtBjTjGXV8ilCm0TU2Fe14eChfR/view?usp=sharing) or from my old post [#25](https://github.com/BreakBB/ExtendedCharacterStats/issues/25#issuecomment-633207116) 

2. Rename`ExtendedCharacterStats/Modules/i18n/`**en.lua** in `ExtendedCharacterStats/Modules/i18n/`**OLDen.lua**

3. Rename **fr.lua** that you'v downloaded in **en.lua** and put it in `ExtendedCharacterStats/Modules/i18n/`

Greetings ! 😀

PS1: Et si tu vois une erreur de traduction ou d'orthographe merci de me la remonter pour que je la corrige ! 🤓

PS2: Yes I changed my username to Chironeyes -> GeekToBe1 no more exist 😅

**Comment by Chironeyes** [comment]
Hi dear edbob78 !
 
**Temporary solution til future realease implemented it**

1. Download my french translation from my Google drive [here](https://drive.google.com/file/d/1io2ycxtBjTjGXV8ilCm0TU2Fe14eChfR/view?usp=sharing) or from my old post [#25](https://github.com/BreakBB/ExtendedCharacterStats/issues/25#issuecomment-633207116) 

2. Rename line N°6 from downloaded file **fr.lua** from `function i18n:UseFrench()` to `function i18n:UseEnglish()`

3. Rename`ExtendedCharacterStats/Modules/i18n/`**en.lua** in `ExtendedCharacterStats/Modules/i18n/`**OLDen.lua**

4. Rename **fr.lua** that you'v downloaded in **en.lua** and put it in `ExtendedCharacterStats/Modules/i18n/`

Greetings ! 😀

PS1: Et si tu vois une erreur de traduction ou d'orthographe merci de me la remonter pour que je la corrige ! 🤓

PS2: Yes I changed my username to Chironeyes -> GeekToBe1 no more exist 😅

**Comment by Chironeyes** [comment]
Hi dear @edbob78  !

**Temporary solution til future realease implemented it**

1. Download french translation from my Google drive [here](https://drive.google.com/file/d/1io2ycxtBjTjGXV8ilCm0TU2Fe14eChfR/view?usp=sharing) or from my old post #25 

2. Rename **line N°6** of downloaded file **fr.lua** from `function i18n:UseFrench()` to `function i18n:UseEnglish()`

3. Rename file `ExtendedCharacterStats/Modules/i18n/`**en.lua** in `ExtendedCharacterStats/Modules/i18n/`**OLD_en.lua**

4. Rename file **fr.lua** that you'v downloaded and modified to **en.lua** and put it in `ExtendedCharacterStats/Modules/i18n/`

Greetings ! 😀

PS1: Et si tu vois une erreur de traduction ou d'orthographe merci de me la remonter pour que je la corrige ! 🤓

PS2: Yes I changed my username to Chironeyes -> GeekToBe1 no more exist 😅

**Comment by edbob78** [comment]
Hi

Thanks for the quick workaround, works fine =)
Actually I didn't even realise it was in english until now, some things sound a bit weird in french^^
I'd change few things:

- manquer->chances de rater (everywhere)

- Mp5 (Objects) -> Mp5 (Objets)

- Spell -> Sorts
                          
Cheers!

**Comment by Chironeyes** [comment]
@edbob78 Thanks for the corrections !

I have rectified the [**fr.lua**](https://drive.google.com/file/d/1io2ycxtBjTjGXV8ilCm0TU2Fe14eChfR/view?usp=sharing) file from your vettings 👍 
You can download it from the same link 😉 

Greetings !

**Comment by BreakBB** [comment]
@Chironeyes Do you think you can check the latest master (today ?) and translate the new UI options I added? I would like to release a new version soon.

**Comment by Chironeyes** [comment]
@BreakBB Yes I will do it in two hours ASAP.

**Comment by BreakBB** [comment]
@Chironeyes Awesome 😍

**Comment by Chironeyes** [comment]
@BreakBB That's done ! But I have one question : What do you mean about line 39 ["FULL"] parameter ? All colors ?
[fr.lua with new UI options translated](https://drive.google.com/file/d/1io2ycxtBjTjGXV8ilCm0TU2Fe14eChfR/view?usp=sharing)

**Comment by BreakBB** [comment]
@Chironeyes Yes, that is "both". Coloring the text and the values.

**Comment by Chironeyes** [comment]
@BreakBB Okay that's fine I translated  ["FULL"] into "Toutes" meaning "all" :)

**Comment by BreakBB** [comment]
@Chironeyes Perfect 👍 Thank you very much for the quick help. I just released v2.5.0 here on GitHub and also on Curseforge 😁 A lot of MP5 fixes.
