### ISSUE TITLE
Tier 1 warrior set bonus being counted incorrectly

### ISSUE THREAD

**Issue by sir-galahad** [BreakBB/ExtendedCharacterStats#59]
## Bug description
Warrior t1 3piece set bonus is 30 block value
1. I found that when i have 3 pieces of warrior t1 (gloves, chest, bracers) equipped and no other gear my block value is 7, so the block value is being calculated soley through my str stat. 
2. when i equip the elementium reinforced bulwark my shield block value jumps up to 110
3. if i then equip the gauntlets of wrath breaking the t1 set bonus my block value remains the same
4. if i re-equip the gauntlets of might (restoring the set bonus) my block value shows as 80

## Screenshots
![image](https://user-images.githubusercontent.com/8272140/91901280-0012a100-ec6e-11ea-8069-acbd1d6abaed.png)

![image](https://user-images.githubusercontent.com/8272140/91901334-128cda80-ec6e-11ea-8b90-559e0e88bee2.png)

![image](https://user-images.githubusercontent.com/8272140/91901389-28020480-ec6e-11ea-82f6-c17cf45b7b4b.png)
![image](https://user-images.githubusercontent.com/8272140/91901465-3e0fc500-ec6e-11ea-92d5-dc0e72058662.png)

## Version
ECS v2.4.6

**Comment by Chironeyes** [comment]
@sir-galahad Have you try to reproduce this on the last 2.5 version of ECS ?
You can download it from [https://github.com/BreakBB/ExtendedCharacterStats/releases/tag/v2.5.0](https://github.com/BreakBB/ExtendedCharacterStats/releases/tag/v2.5.0)

**Comment by BreakBB** [comment]
@sir-galahad Hey thanks for this report. I was never able to test this and nobody reported this before you. I will look into it to see what's up. The new version already liked above might fix some of the issues, but the set bonus is not included yet.

**Comment by sir-galahad** [comment]
noted.  i'll give it a shot :)

**Comment by sir-galahad** [comment]
i've just tested with 2.5.0, and have the same results.

for what it's worth i've tested a couple of other sets with bonuses that add a flat stat (bloodvine, sorcerer's, zandalar illusionist's) and found no issues with those

**Comment by BreakBB** [comment]
@sir-galahad Thanks for testing those as well! I will make sure to fix this soon ™️
