### ISSUE TITLE
Visual

### ISSUE THREAD

**Issue by saralhenil** [BreakBB/ExtendedCharacterStats#64]
![2020-09-09_LI](https://user-images.githubusercontent.com/27927465/92599633-cfa0b780-f2aa-11ea-86f7-9e86c0fce405.jpg)

**Comment by Chironeyes** [comment]
Salut à toi, il y a un paramètre quand tu cliques sur le bouton **Paramètres** -> Onglet **Générale** -> Slider **Largeur de fenêtre** et qui permet de modifier la largeur de la fenêtre des statistiques.

Cela à résolu ton problème ?

**Comment by saralhenil** [comment]
Je regarde ça des que je le co merci.

Le mer. 9 sept. 2020 à 17:35, Chiron Sceptique <notifications@github.com> a
écrit :

**Comment by BreakBB** [comment]
Hey @saralhenil as Chironeyes (most likely) already told you: You can adjust/change the window width in the settings of ECS 👍
