### ISSUE TITLE
Bad French word translation

### ISSUE THREAD

**Issue by Chironeyes** [BreakBB/ExtendedCharacterStats#65]
## Bug description
There is a bad translation in fr.lua file. It's about **Général** word. 
Before it had a "e" letter on its end. So this is wrong -> _Générale_

### Modifications :
1. Line 24 : ["GENERAL"] = "**Général**"
2. Line 49 : ["MELEE_SETTINGS"] = "Mêlée **Général**" 
3. Line 62 : ["RANGED_SETTINGS"] = "À distance **Général**"
4. Line 75 : ["DEFENSE_SETTINGS"] = "Défense **Général**"
5. Line 90 : ["MANA_SETTINGS"] = "Mana **Général**"
6. Line 99 : ["SPELL_SETTINGS"] = "Sorts **Général**"

You can get the corrected file [here](https://drive.google.com/file/d/1io2ycxtBjTjGXV8ilCm0TU2Fe14eChfR/view?usp=sharing)

## Version
ECS 2.5 and before

**Comment by BreakBB** [comment]
@Chironeyes Thanks once again 👍
