### ISSUE TITLE
Missing translation for <MOVEMENT_SPEED> key

### ISSUE THREAD

**Issue by cbracht** [BreakBB/ExtendedCharacterStats#69]
## Bug description
On character log in or when mounting and dismounting, the error message "Missing translation for <MOVEMENT_SPEED> key" is output in the chat box. Client language is german.

## Screenshots
![image](https://user-images.githubusercontent.com/1489764/93748685-f4752300-fbf8-11ea-810c-42377cb02ee4.png)

## Version
ECS v2.6.0

Thank you!

Edit: Possibly use english language as default, when a translated text is missing?

**Comment by BreakBB** [comment]
@cbracht Argh, damn. Sorry for that, I will release an update in a few hours!

Also yes, switching to English should be possible, I will investiagate that :)

**Comment by pierre-r** [comment]
Hello,

I can't pull request right now, but if that can help you, here the French version :

```
 ["MOVEMENT_SPEED_SETTING"] = "Affiche la vitesse de déplacement",
 ["MOVEMENT_SPEED_SETTING_DESC"] = "Affiche/Cache la vitesse de déplacement.",
-- Stats
["MOVEMENT_SPEED"] = "Vitesse de déplacement: ",
```

**Comment by BreakBB** [comment]
@pierre-r That helps indeed, thank you very much :+1:

**Comment by cbracht** [comment]
@BreakBB Thank you for your fix. Keep up your great work!

**Comment by BreakBB** [comment]
@cbracht Thanks for reporting the issue :grin:

**Comment by habkeinGeld** [comment]
i had the same issue my Problem was the new Version of the Addon: "Extended Character Stats"
