### ISSUE TITLE
2.6.0 'GetMovementSpeed' bug 

### ISSUE THREAD

**Issue by yanyosuten** [BreakBB/ExtendedCharacterStats#70]
## Bug description

Updated the addon and it stopped working. 

## Screenshots

Date: 2020-09-21 11:53:14
ID: 1
Error occured in: Global
Count: 1
Message: ...\AddOns\ExtendedCharacterStats\Modules\Data\Data.lua line 47:
   attempt to call method 'GetMovementSpeed' (a nil value)
Debug:
   ...\AddOns\ExtendedCharacterStats\Modules\Data\Data.lua:47: GetStatInfo()
   ...face\AddOns\ExtendedCharacterStats\Modules\Stats.lua:153:
      ...face\AddOns\ExtendedCharacterStats\Modules\Stats.lua:151
   ...face\AddOns\ExtendedCharacterStats\Modules\Stats.lua:145: _CreateStatInfo()
   ...face\AddOns\ExtendedCharacterStats\Modules\Stats.lua:174:
      ...face\AddOns\ExtendedCharacterStats\Modules\Stats.lua:170
   ...face\AddOns\ExtendedCharacterStats\Modules\Stats.lua:87: CreateWindow()
   ExtendedCharacterStats\ECS.lua:86:
      ExtendedCharacterStats\ECS.lua:84
   ExtendedCharacterStats\ECS.lua:33:
      ExtendedCharacterStats\ECS.lua:26
Locals:
self = <table> {
 HUNTER = 3
 FIRE_SCHOOL = 3
 HOLY_SCHOOL = 2
 ROGUE = 4
 MAGE = 8
 GetMP5WhileCasting = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\MP5.lua:70
 SpellHitBonus = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\SpellHit.lua:23
 GetBlockValue = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\Defense.lua:71
 DRUID = 11
 GetMP5FromSpirit = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\MP5.lua:60
 RangedCrit = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\Ranged.lua:30
 MeleeHitBonus = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\Melee.lua:19
 SpellMissChanceBossLevel = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\SpellHit.lua:51
 WARLOCK = 9
 GetParryChance = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\Defense.lua:61
 SpellMissChanceSameLevel = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\SpellHit.lua:33
 GetSpellCrit = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\SpellCrit.lua:15
 GetMP5FromBuffs = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\MP5.lua:111
 GetRangeAttackPower = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\Ranged.lua:12
 HasNatureCritBonusModifier = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\ItemSets.lua:91
 MeleeHitMissChanceSameLevel = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\Melee.lua:24
 SHADOW_SCHOOL = 6
 SHAMAN = 7
 SpellPenetration = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\Data.lua:33
 NATURE_SCHOOL = 4
 ARCANE_SCHOOL = 7
 RangeMissChanceBossLevel = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\Ranged.lua:76
 GetSpellDmg = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\Data.lua:13
 GetArmorValue = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\Defense.lua:10
 RangeHitBonus = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\Ranged.lua:53
 GetHealingPower = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\Data.lua:38
 private = <table> {
 }
 MeleeCrit = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\Melee.lua:14
 MeleeHitMissChanceBossLevel = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\Melee.lua:51
 WARRIOR = 1
 GetMeleeAttackPower = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\Melee.lua:8
 GetDodgeChance = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\Defense.lua:56
 PALADIN = 2
 FROST_SCHOOL = 5
 GetBlockChance = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\Defense.lua:66
 HasSetBonusModifierBlockValue = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\ItemSets.lua:98
 RangeMissChanceSameLevel = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\Ranged.lua:58
 PRIEST = 5
 GetDefenseValue = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\Defense.lua:16
 GetMP5FromItems = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\MP5.lua:11
 HasSetBonusModifierMP5 = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\ItemSets.lua:73
 setNames = <table> {
 }
 GetStatInfo = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\Data.lua:44
 GetSetBonusValueMP5 = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\ItemSets.lua:81
 enchantIds = <table> {
 }
 PHYSICAL_SCHOOL = 1
}
refName = "MovementSpeed"
(*temporary) = nil
(*temporary) = <table> {
 HUNTER = 3
 FIRE_SCHOOL = 3
 HOLY_SCHOOL = 2
 ROGUE = 4
 MAGE = 8
 GetMP5WhileCasting = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Data\MP5.lua:70
 SpellHitBonus = <function> defined @Interface\AddOns\E
AddOns:
  Swatter, v8.2.6511 (SwimmingSeadragon)
  AddOnSkins, v4.44
  AtlasLootClassic, vv1.5.6
  AtlasLootClassicData, vv1.5.6
  AtlasLootClassicDungeonsAndRaids, vv1.5.6
  AucAdvanced, v8.2.6471 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6497 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6499 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6503 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6500 (SwimmingSeadragon)
  AucStatSimple, v8.2.6501 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6502 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6504 (SwimmingSeadragon)
  BeanCounter, v8.2.6505 (SwimmingSeadragon)
  CommunityDKP, v3.2.3
  DBMCore, v1.13.60
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Details, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  ElvUI, v1.31
  ElvUIEasyBuff, v1.1.7
  ElvUINutsAndBoltsClassic, v1.03
  ElvUIRedtuzkClassic, v1.3.0
  ElvUIShadows, v1.0
  Enchantrix, v8.2.6506 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6507 (SwimmingSeadragon)
  ExtendedCharacterStats, v2.5.0
  FishingBuddy, v0.7.3 Beta 7
  GatherMate2, v1.45.5
  Immersion, v1.2.3
  Informant, v8.2.6508 (SwimmingSeadragon)
  ItemRack, v
  NauticusClassic, v1.3.1
  NovaWorldBuffs, v1.79
  Questie, v6.0.5
  Stubby, v8.2.6510 (SwimmingSeadragon)
  TidyPlatesThreatPlates, v1.4.5
  WeakAuras, v2.18.4
  BlizRuntimeLib_enUS v1.13.5.11305 <none>
  (ck=528)

## Version

2.6.0

**Comment by BreakBB** [comment]
@yanyosuten Are you using this addon on Classic?

**Comment by yanyosuten** [comment]
yes

**Comment by yanyosuten** [comment]
@BreakBB my bad - it seems to have been caused by updating the addon mid game, restart seems to have resolved it.

**Comment by BreakBB** [comment]
@yanyosuten Ah yes. Whenever you update an addon you should make sure to restart WoW. Otherwise new files won't be loaded by the game :+1:
