### ISSUE TITLE
Blessing of Wisdom with talent MP5 gain

### ISSUE THREAD

**Issue by Dropbooster** [BreakBB/ExtendedCharacterStats#71]
## Bug description

Holy Paladin with talent Improved Blessing of Wisdom have +40 mp5 instead base 33 (+20%).

also Movement Speed bonus does not fit to window.

## Screenshots

![image](https://user-images.githubusercontent.com/71389658/93812447-4bf7ab00-fc5a-11ea-9696-8c4856397d07.png)
![image](https://user-images.githubusercontent.com/71389658/93812468-54e87c80-fc5a-11ea-9b0e-88f64ff0d2ea.png)

## Version

2.6.1

**Comment by BreakBB** [comment]
@Dropbooster Check the settings to change the width of the window.

Thanks for the report of the paladin talent, will be an easy fix 👍

**Comment by BreakBB** [comment]
This is fixed by 00e5c1c4d3bdd3426dbd3c8b7b4c9d029466ef31

Also other players can't see the buffed version (neither in the buff nor in a stat window like ECS). So only the paladin casting BoW on himself sees that it is a buffed version.
