### ISSUE TITLE
Holy Spell Crit Value Issue

### ISSUE THREAD

**Issue by TristramGoose** [BreakBB/ExtendedCharacterStats#73]
## Bug description

I noticed my holy spell crit values were higher in this addon vs the character stats classic addon. I was testing the character stats classic addon to see if that was where the issue lay by unlearning my talents then relearning all the talents in the holy tree up to but not including holy power then running /dump GetSpellCritChance(2) in chat to get a base line spell crit value. 

I then put 5 points into holy power and ran it again and it took the extra 5% crit from my talents into account. The addon took it into account as well and the values matched. ECS however seems to add another 5% on top of that for some reason.

## Screenshots

These screenshots are from a 2nd identical test because I forgot to take them the first time. This is why I am always poor...  
![Crit with talent ECS on](https://user-images.githubusercontent.com/30111689/94007582-a6cef680-fd6f-11ea-8d65-1adad86400d1.jpg)
![Crit without talent](https://user-images.githubusercontent.com/30111689/94007595-ab93aa80-fd6f-11ea-863a-e3893074da73.jpg)

## Version

Version 2.6.1

**Comment by pvanloo** [comment]
Nice report!

If GetSpellCritChance returns the modified %, following should not be called. I'll make a PR 👍 

https://github.com/BreakBB/ExtendedCharacterStats/blob/47fc10654e1183aeea86822787bf411466c9ae2e/Modules/Data/SpellCrit.lua#L57

**Comment by BreakBB** [comment]
I wonder if Blizzard corrected other API values as well 🤔 Thanks for the report 👍
