### ISSUE TITLE
Extended Character Stats

### ISSUE THREAD

**Issue by mvt111** [BreakBB/ExtendedCharacterStats#84]
The extended character stats not working correctly....has the following error message.  Update in CurseForge is current.

Date: 2020-12-09 22:20:34
ID: 1
Error occured in: Global
Count: 1
Message: ...\AddOns\ExtendedCharacterStats\Modules\GearInfos.lua line 81:
   attempt to index field 'qualityTexture' (a nil value)
Debug:
   ...\AddOns\ExtendedCharacterStats\Modules\GearInfos.lua:81: ToggleColorFrames()
   ...\AddOns\ExtendedCharacterStats\Modules\GearInfos.lua:41:
      ...\AddOns\ExtendedCharacterStats\Modules\GearInfos.lua:33
   ...\AddOns\ExtendedCharacterStats\Modules\GearInfos.lua:29: Init()
   ExtendedCharacterStats\ECS.lua:89:
      ExtendedCharacterStats\ECS.lua:85
   ExtendedCharacterStats\ECS.lua:34:
      ExtendedCharacterStats\ECS.lua:27
Locals:
self = <table> {
 UpdateInspectGearColorFrames = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\GearInfos.lua:110
 Init = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\GearInfos.lua:28
 private = <table> {
 }
 ToggleColorFrames = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\GearInfos.lua:71
 UpdateGearColorFrames = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\GearInfos.lua:45
}
value = true
(for generator) = <function> defined =[C]:-1
(for state) = <table> {
 1 = InspectHeadSlot {
 }
 2 = InspectNeckSlot {
 }
 3 = InspectShoulderSlot {
 }
 4 = InspectBackSlot {
 }
 5 = InspectChestSlot {
 }
 6 = InspectWristSlot {
 }
 7 = InspectHandsSlot {
 }
 8 = InspectWaistSlot {
 }
 9 = InspectLegsSlot {
 }
 10 = InspectFeetSlot {
 }
 11 = InspectFinger0Slot {
 }
 12 = InspectFinger1Slot {
 }
 13 = InspectTrinket0Slot {
 }
 14 = InspectTrinket1Slot {
 }
 15 = InspectMainHandSlot {
 }
 16 = InspectSecondaryHandSlot {
 }
 17 = InspectRangedSlot {
 }
}
(for control) = 1
_ = 1
gearFrame = InspectHeadSlot {
 0 = <userdata>
 checkRelic = false
 Count = InspectHeadSlotCount {
 }
 IconBorder = <unnamed> {
 }
 backgroundTextureName = 136516
 searchOverlay = InspectHeadSlotSearchOverlay {
 }
 icon = InspectHeadSlotIconTexture {
 }
 IconOverlay = <unnamed> {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'qualityTexture' (a nil value)"
GEAR_SLOT_FRAMES = <table> {
 1 = CharacterHeadSlot {
 }
 2 = CharacterNeckSlot {
 }
 3 = CharacterShoulderSlot {
 }
 4 = CharacterBackSlot {
 }
 5 = CharacterChestSlot {
 }
 6 = CharacterWristSlot {
 }
 7 = CharacterHandsSlot {
 }
 8 = CharacterWaistSlot {
 }
 9 = CharacterLegsSlot {
 }
 10 = CharacterFeetSlot {
 }
 11 = CharacterFinger0Slot {
 }
 12 = CharacterFinger1Slot {
 }
 13 = CharacterTrinket0Slot {
 }
 14 = CharacterTrinket1Slot {
 }
 15 = CharacterMainHandSlot {
 }
 16 = CharacterSecondaryHandSlot {
 }
 17 = CharacterRangedSlot {
 }
}
_GetInspectGearSlots = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\GearInfos.lua:88

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AngryAssignments, vv1.13.2c
  AtlasLootClassic, vv1.5.8
  AtlasLootClassicData, vv1.5.8
  AtlasLootClassicDungeonsAndRaids, vv1.5.8
  AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  Bagnon, v9.0.4
  ClassicAggroHighlight, vv1.3.0
  ClassicCastbars, vv1.3.15
  ClassicCastbarsOptions, v
  ClassicGuildBank, v1.3
  ClassicLootAssistant, v
  CommunityDKP, v3.2.3
  DBMCore, v1.13.63-9-g261814a
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  ExtendedCharacterStats, v2.6.3
  GatherMate2, v1.45.5
  GTFO, v4.55
  GuildRosterManager, v1.926
  GuildLotteryRaffle, v3.1.25
  Informant, v8.2.6374 (SwimmingSeadragon)
  InspectListCreator, v0.2
  LeatrixMaps, v1.13.88
  LootReserve, v2020-11-03
  Outfitter, v1.3.0
  PallyPower, vv1.2.27-classic
  Pawn, v2.4.7
  Plater, vPlater-1.13.5.95-Classic
  Questie, v6.2.3
  RaidSummon, v3.4.1
  Recount, vv1.13.5c
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  ThreatClassic2, v2.27
  TranqRotate, v1.5.0
  WeakAuras, v3.1.3
  WeaponSwingTimer, v4.1.0
  WhatsUp, v2.0
  BlizRuntimeLib_enUS v1.13.6.11306 <none>
  (ck=61e)

**Comment by BreakBB** [comment]
Hey @mvt111 thanks for reaching out about this. Can you explain what you did when this error appeared? Or is this what happens when you log in?
