### ISSUE TITLE
MP5 (Spirit) is wrong.

### ISSUE THREAD

**Issue by Laumesis** [BreakBB/ExtendedCharacterStats#85]
## Bug description
MP5 (Spirit) value is incorrect compared to real mana gains over time in pure spirit gear.

Reason is in MP5.lua, function Data:GetMP5FromSpirit():
`return DataUtils:Round(base, 0) * 5`
Should instead be:
`return DataUtils:Round(base*5, 0)`

I would also suggest showing the value with one decimal: `return DataUtils:Round(base*5, 1)`

## Version
v2.6.3

**Comment by Laumesis** [comment]
If you would calculate Mana Regen from spirit, then you would need flooring before multiplying. But you are using ready value from game api.

**Comment by BreakBB** [comment]
Hey @Laumesis Thank you very much for this finding! 👍 I just corrected this and hope to push an update in the next days. Time is very limited atm 🙈
