### ISSUE TITLE
Add equipped item list + enchant tooltip

### ISSUE THREAD

**Issue by promaori** [BreakBB/ExtendedCharacterStats#88]
## Description
Add a window of equipped items alongside the character stat pane. This mirrors the functionality of MerInspect which isn't actively developed for Classic but ECS also tracks stats are more meticulously in comparison.

**Comment by BreakBB** [comment]
Hey @promaori thanks for this suggestion. But could you explain (or maybe show) what exactly you want. I found this:

![grafik](https://user-images.githubusercontent.com/33514570/103988837-09b59380-518f-11eb-808f-1b60af93c591.png)

So you want another frame next to the ECS frame which lists all the items you have equipped? This could be an optional window which is toggled from the ECS frame. Together with the regular character frame and the ECS window, the screen would be full quite fast.

**Comment by BreakBB** [comment]
I no longer think this is in scope of ECS
