### ISSUE TITLE
Addon doesn't appear to be loading

### ISSUE THREAD

**Issue by Smokeyjoe91** [BreakBB/ExtendedCharacterStats#92]
## Bug description

The previous version of the addon works fine, but the updated addon isn't working at all.
Keep in mind I didn't update from a previous version, I installed the latest version, saw it wasn't working, and tried the previous version that's working just fine. 
I tried updating after installing the previous version and it kindaaaaa loads, the box next to the character is completely empty.
Im running Windows 10 x64

**Comment by BreakBB** [comment]
Hey @Smokeyjoe91 I totally missed the notifications of Curseforge and GitHub. So I didn't see people have trouble with ECS. Sorry for this, I will push a fix for this tomorrow morning

**Comment by BreakBB** [comment]
Please try the updated version I just published. You can get it on CurseForge as always.
