### ISSUE TITLE
ECS crashes on character login

### ISSUE THREAD

**Issue by bsjustice** [BreakBB/ExtendedCharacterStats#94]
## Bug description

This happens everytime I log into a character.

## Screenshots

Date: 2021-01-14 14:04:33
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\ExtendedCharacterStats\ECS.lua line 48:
   attempt to index field 'general' (a nil value)
Debug:
   [C]: ?
   ExtendedCharacterStats\ECS.lua:48:
      ExtendedCharacterStats\ECS.lua:41
   ExtendedCharacterStats\ECS.lua:31:
      ExtendedCharacterStats\ECS.lua:28
Locals:

AddOns:
  Swatter, v8.2.6377 (SwimmingSeadragon)
  AtlasLootClassic, vv1.5.8
  AtlasLootClassicData, vv1.5.8
  AtlasLootClassicDungeonsAndRaids, vv1.5.8
 AucAdvanced, v8.2.6430 (SwimmingSeadragon)
  aucadvancedsearcherpawn, v1.6.2-classic
  AucFilterBasic, v8.2.6364 (SwimmingSeadragon)
  AucStatHistogram, v8.2.6366 (SwimmingSeadragon)
  AucStatiLevel, v8.2.6370 (SwimmingSeadragon)
  AucStatPurchased, v8.2.6367 (SwimmingSeadragon)
  AucStatSimple, v8.2.6399 (SwimmingSeadragon)
  AucStatStdDev, v8.2.6369 (SwimmingSeadragon)
  AucUtilFixAH, v8.2.6371 (SwimmingSeadragon)
  BagBrother, v
  BagFreeSpaceCounter, v1.0.4
  Bagnon, v9.0.4
  Bartender4, v4.10.6
  BattlegroundTargets, v11305-1
  BeanCounter, v8.2.6434 (SwimmingSeadragon)
  BetterVendorPrice, vv1.13.12
  ClassicAuraDurations, v1.13.61
  ClassicCastbars, vv1.3.16
  ClassicCastbarsOptions, vv1.3.16
  DBMCore, v1.13.67
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Decursive, v2.7.8
  Details, v
  DetailsStreamer, v
  DetailsTinyThreat, v
  Enchantrix, v8.2.6428 (SwimmingSeadragon)
  EnchantrixBarker, v8.2.6469 (SwimmingSeadragon)
  ExtendedCharacterStats, v2.7.0
  Pawn, v2.4.10
  SlideBar, v8.2.6375 (SwimmingSeadragon)
  Stubby, v8.2.6376 (SwimmingSeadragon)
  BlizRuntimeLib_enUS v1.13.6.11306 <none>
  (ck=4f1)

![image](https://user-images.githubusercontent.com/77458193/104637609-0c265a80-5673-11eb-8094-944f3d737bea.png)

## Version

2.7, the latest version from Curseforge via Overwolf

**Comment by BreakBB** [comment]
Please try the updated version I just published. You can get it on CurseForge as always.
