### ISSUE TITLE
wont load, gives lua error and following message

### ISSUE THREAD

**Issue by charliemorales** [BreakBB/ExtendedCharacterStats#95]
Message: ...face\AddOns\ExtendedCharacterStats\Modules\Stats.lua:44: attempt to index field 'general' (a nil value)
Time: Sat Jan 16 23:37:32 2021
Count: 1
Stack: ...face\AddOns\ExtendedCharacterStats\Modules\Stats.lua:44: attempt to index field 'general' (a nil value)
...face\AddOns\ExtendedCharacterStats\Modules\Stats.lua:44: in function `CreateWindow'
Interface\AddOns\ExtendedCharacterStats\ECS.lua:102: in function <Interface\AddOns\ExtendedCharacterStats\ECS.lua:100>
Interface\AddOns\ExtendedCharacterStats\ECS.lua:35: in function <Interface\AddOns\ExtendedCharacterStats\ECS.lua:28>

Locals: self = <table> {
 HideWindow = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Stats.lua:128
 UpdateInformation = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Stats.lua:295
 UpdateWindowSize = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Stats.lua:108
 RebuildStatInfos = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Stats.lua:282
 RecycleFrame = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Stats.lua:276
 GetFrame = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Stats.lua:137
 CreateWindow = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Stats.lua:40
 private = <table> {
 }
 UpdateSettingsButtonText = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Stats.lua:113
 GetDisplayedLines = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Stats.lua:142
 ToggleWindow = <function> defined @Interface\AddOns\ExtendedCharacterStats\Modules\Stats.lua:118
}
ecs = <table> {
}
mainFrame = ECS_StatsFrame {
 0 = <userdata>
 TitleText = <unnamed> {
 }
 RightBorder = <unnamed> {
 }
 LeftBorder = <unnamed> {
 }
 InsetBorderTopLeft = <unnamed> {
 }
 TopRightCorner = <unnamed> {
 }
 TopLeftCorner = <unnamed> {
 }
 Bg = <unnamed> {
 }
 TopBorder = <unnamed> {
 }
 InsetBg = <unnamed> {
 }
 TopTileStreaks = <unnamed> {
 }
 TitleBg = <unnamed> {
 }
 BottomBorder = <unnamed> {
 }
 InsetBorderRight = <unnamed> {
 }
 InsetBorderLeft = <unnamed> {
 }
 InsetBorderBottomLeft = <unnamed> {
 }
 CloseButton = <unnamed> {
 }
 InsetBorderBottom = <unnamed> {
 }
 InsetBorderTop = <unnamed> {
 }
 BotLeftCorner = <unnamed> {
 }
 InsetBorderTopRight = <unnamed> {
 }
 InsetBorderBottomRight = <unnamed> {
 }
 BotRightCorner = <unnamed> {
 }
}
(*temporary) = <function> defined =[C]:-1
(*temporary) = ECS_StatsFrame {
 0 = <userdata>
 TitleText = <unnamed> {
 }
 RightBorder = <unnamed> {
 }
 LeftBorder = <unnamed> {
 }
 InsetBorderTopLeft = <unnamed> {
 }
 TopRightCorner = <unnamed> {
 }
 TopLeftCorner = <unnamed> {
 }
 Bg = <unnamed> {
 }
 TopBorder = <unnamed> {
 }
 InsetBg = <unnamed> {
 }
 TopTileStreaks = <unnamed> {
 }
 TitleBg = <unnamed> {
 }
 BottomBorder = <unnamed> {
 }
 InsetBorderRight = <unnamed> {
 }
 InsetBorderLeft = <unnamed> {
 }
 InsetBorderBottomLeft = <unnamed> {
 }
 CloseButton = <unnamed> {
 }
 InsetBorderBottom = <unnamed> {
 }
 InsetBorderTop = <unnamed> {
 }
 BotLeftCorner = <unnamed> {
 }
 InsetBorderTopRight = <unnamed> {
 }
 InsetBorderBottomRight = <unnamed> {
 }
 BotRightCorner = <unnamed> {
 }
}
(*temporary) = nil
(*temporary) = "BasicFrameTemplateWithInset"
(*temporary) = ECS_StatsFrame {
 0 = <userdata>
 TitleText = <unnamed> {
 }
 RightBorder = <unnamed> {
 }
 LeftBorder = <unnamed> {
 }
 InsetBorderTopLeft = <unnamed> {
 }
 TopRightCorner = <unnamed> {
 }
 TopLeftCorner = <unnamed> {
 }
 Bg = <unnamed> {
 }
 TopBorder = <unnamed> {
 }
 InsetBg = <unnamed> {
 }
 TopTileStreaks = <unnamed> {
 }
 TitleBg = <unnamed> {
 }
 BottomBorder = <unnamed> {
 }
 InsetBorderRight = <unnamed> {
 }
 InsetBorderLeft = <unnamed> {
 }
 InsetBorderBottomLeft = <unnamed> {
 }
 CloseButton = <unnamed> {
 }
 InsetBorderBottom = <unnamed> {
 }
 InsetBorderTop = <unnamed> {
 }
 BotLeftCorner = <unnamed> {
 }
 InsetBorderTopRight = <unnamed> {
 }
 InsetBorderBottomRight = <unnamed> {

**Comment by BreakBB** [comment]
Thanks for the report, I will push a fix for this tomorrow morning! Sorry for the trouble

**Comment by BreakBB** [comment]
Please try the updated version I just published. You can get it on CurseForge as always.
