### ISSUE TITLE
Failure in wow after installing extended charakter stats

### ISSUE THREAD

**Issue by huckgermany** [BreakBB/ExtendedCharacterStats#96]
See screenshot
![extended charakter stats failure](https://user-images.githubusercontent.com/77568799/104836531-c3f37c00-58ae-11eb-8f33-ad7f7d033412.PNG)

**Comment by BreakBB** [comment]
Hey @huckgermany 

Thanks for the report. Another user has the same issue.

Did you install it for the first time/after a clean installation?

I will try to push out a fix for this tomorrow!

**Comment by huckgermany** [comment]
HI Björn,
No I have the addon quite awhile without a problem. This failure appeared
just a few days ago. Now I deletes the addon and evetything is fine.
Great to get feedback as soon as it is fixed.
Thx
Hubert

Björn Böing <notifications@github.com> schrieb am So., 17. Jan. 2021, 22:55:

**Comment by BreakBB** [comment]
Please try the updated version I just published. You can get it on CurseForge as always.

**Comment by huckgermany** [comment]
Hi,
great, just installed the new version. Bug is gone now.
Good job!
rgds
Hubert
