### ISSUE TITLE
Bug no Settings availabe

### ISSUE THREAD

**Issue by tiegars** [BreakBB/ExtendedCharacterStats#97]
## Bug description

New Version cant set settings. I can click the button but nothing show.
Can't move the window from esc. I use german client.
Sorry for my english.
 

## Screenshots

![WoWScrnShot_011821_082745](https://user-images.githubusercontent.com/21026222/104884971-8999e580-5967-11eb-927c-739e14f29de4.jpg)

**Comment by BreakBB** [comment]
Hey @tiegars I am sorry to tell you, but ExtendedCharacterStats is for WoW Classic only. All the values it shows are already shown by the default Blizzard UI on retail.
