### ISSUE TITLE
Status does not appear

### ISSUE THREAD

**Issue by guilherme-rs** [BreakBB/ExtendedCharacterStats#98]
## Bug description
The status info dont show when im playing with druid, but when i play with others chars its shows normally.

## Screenshots
![image](https://user-images.githubusercontent.com/7820211/105190787-1f26a800-5b15-11eb-88e8-6a6b1f617d7a.png)

![image](https://user-images.githubusercontent.com/7820211/105191472-dfac8b80-5b15-11eb-89e2-3fac86ba595c.png)

## Version
2.7.0
-->

**Comment by BreakBB** [comment]
Hey @guilherme-rs there already is a v2.7.1 version available [on CurseForge](https://www.curseforge.com/wow/addons/extended-character-stats) and here [on Github](https://github.com/BreakBB/ExtendedCharacterStats/releases/tag/v2.7.1). That should fix your issue.

ECS had a problem for new/fresh installations which also effect "new" characters.

Please update and let me know if the new version fixes your issue 👍

**Comment by guilherme-rs** [comment]
Fixed with update.
